### ISSUE TITLE
Please tell us how install v12 discord.js

### ISSUE THREAD

**Issue by Zaid-maker** [ZerioDev/Music-bot#1]
I have use the source code and make my discord bot but wehn i use the command it say's UnhandledPromiseRejectionWarning: #<object> also tell us how we use the commands

**Comment by ZerioDev** [comment]
Hi, to install v12 (Discord.js) enter this code on console 🙂

```npm install discord.js```

And

```npm uninstall discord.js && npm i discordjs/discord.js```

**Comment by Zaid-maker** [comment]
Ok thank you

**Comment by Zaid-maker** [comment]
Also make a join command it will let the bot join the voice channel.

**Comment by Zaid-maker** [comment]
Still Getting the same error on using any of the command.
```js
(node:911) UnhandledPromiseRejectionWarning: #<Object>
(node:911) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:911) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
