### ISSUE TITLE
how to use ytdlRequestOptions

### ISSUE THREAD

**Issue by AnshhSingh** [ZerioDev/Music-bot#103]
how to use ytdl request options for adding cookies? I am getting rate limit issues so I thought adding cookies should fix it

**Comment by ZerioDev** [comment]
Hey 👋

You might be able to use `ytdlRequestOptions`.

Like this : 

```js
client.player = new Player(client, { ytdlRequestOptions: ... });
```

**Comment by AnshhSingh** [comment]
thanks!
