### ISSUE TITLE
my bot enter in the call, say "starting" and disconnect

### ISSUE THREAD

**Issue by maurodoarmauro** [ZerioDev/Music-bot#104]
so, i can turn on the bon. 
i start, put a music on chat with the command and when he is starting, didnt play music and disconnect

error:
![image](https://user-images.githubusercontent.com/47175028/110128681-fefa3200-7dbe-11eb-8746-d911df993f6c.png)
:musical_note: - Now playing music into :telephone_receiver:┃𝗖𝗵𝗶𝗹𝗹 ...
:warning: - Music stopped as there is no more music in the queue !

i dont now why and i need help...

**Comment by ZerioDev** [comment]
Hey 👋

You need to install FFmpeg. 
Come to Discord server if you want we can help you.

**Comment by maurodoarmauro** [comment]
whats your discord server?

**Comment by ZerioDev** [comment]
> whats your discord server?

You can click [here](https://discord.gg/5cGSYV8ZZj) 👍
