### ISSUE TITLE
Bot not playing music in vc

### ISSUE THREAD

**Issue by oxmc** [ZerioDev/Music-bot#108]
The bot says it's playing but then it disconnects and says no music left in que

**Comment by ViTraX** [comment]
From what I was told, there is a problem with the version of discord-player

**Comment by Kroggieboy57** [comment]
do you have **ffmpeg**?

**Comment by ViTraX** [comment]
Read my message above it's not a FFMpeg problem even if we have the one if bug (The play)

**Comment by arhip144** [comment]
Perhaps your project folder contains spaces in the name. I removed the spaces and it worked for me.

**Comment by oxmc** [comment]
Alright so I have an old version of my project on my old laptop and found that discord-music-player is not installed with npm for some reason. Npm just wont install it.

**Comment by ZerioDev** [comment]
Closed for inactivity !
