### ISSUE TITLE
ERROR: FFMPEG is not installed.

### ISSUE THREAD

**Issue by armfxl** [ZerioDev/Music-bot#109]
I'm getting this error even though I have installed `ffmpeg-static`. I have tried uninstalling and reinstalling.

ERROR: FFMPEG is not installed. Install with "npm install ffmpeg-static" or download it here: https://ffmpeg.org/download.html.
![image](https://user-images.githubusercontent.com/55296171/111067245-b54acf00-84c3-11eb-8305-3e7ca5e810f9.png)

**Comment by Kroggieboy57** [comment]
check the package.json file

**Comment by ChineseUncleTom** [comment]
@Kroggieboy57  
I am trying to run the app in Linux.

I checked the package.json file. I saw "ffmpeg-static": "^4.2.7". Does that means we need the "ffmpeg-static" version 4.2.7?

So I tried the command "npm i ffmpeg-static@4.2.7" to install it. After that, the ERROR still showed up.

I also tried installing ffmpeg globally by following the guide https://www.johnvansickle.com/ffmpeg/faq/. At the end, ffmpeg got installed but the ERROR still showed up.

What do you think about this?

Thanks <3

**Comment by armfxl** [comment]
> @Kroggieboy57
> I am trying to run the app in Linux.
> 
> I checked the package.json file. I saw "ffmpeg-static": "^4.2.7". Does that means we need the "ffmpeg-static" version 4.2.7?
> 
> So I tried the command "npm i ffmpeg-static@4.2.7" to install it. After that, the ERROR still showed up.
> 
> I also tried installing ffmpeg globally by following the guide https://www.johnvansickle.com/ffmpeg/faq/. At the end, ffmpeg got installed but the ERROR still showed up.
> 
> What do you think about this?
> 
> Thanks <3

yeah i still have the issue, can't seem to find a fix.

**Comment by Kroggieboy57** [comment]
hmm where is ffmpeg stored?

**Comment by Schlaager** [comment]
I have the same Issue. tried to install the exact version, that is showed in package.json

**Comment by Kroggieboy57** [comment]
Try storing ffmpeg in the bot folder or join the devs discord server and ask him

**Comment by armfxl** [comment]
> Try storing ffmpeg in the bot folder or join the devs discord server and ask him

the dev did not have an immediate fix himself.

i also tried storing `FFmpeg` in the bot folder with no success.
