### ISSUE TITLE
DiscordAPIError: Invalid Form Body

### ISSUE THREAD

**Issue by ifaisalqz** [ZerioDev/Music-bot#11]
The queue cant handle more than 2000 letters because the DiscordAPI or also the user can't send more than 2000 letters in any channel. so it will be better if you used an embed with pages to using the react to show the other page.

Error: content: Must be 2000 or fewer in length.

**Comment by ZerioDev** [comment]
You beat me to it 👍 
It's planned that an embed be designed with a system of pages !

**Comment by ifaisalqz** [comment]
Nice, good luck then
