### ISSUE TITLE
How To Add More Fields In Help.js and how to add the subfolder in commands file

### ISSUE THREAD

**Issue by swayam-crypto** [ZerioDev/Music-bot#114]

**Comment by Eaves628** [comment]
you can add more fields by .addField (example) (example)
and you can add a subfolder by clicking the folder option when opening the commands folder.

**Comment by swayam-crypto** [comment]
i k this bro i was askimg for help.js if u have give it to me

**Comment by ZerioDev** [comment]
Closed for inactivity !
