### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by MiniWolfy5205** [ZerioDev/Music-bot#117]
Im hosting the bot on https://www.replit.com and i have this error:

/youtube-sr/build/main.js:69
                                    url: item.channel.thumbnails?.default.url,
                                                                 ^

SyntaxError: Unexpected token '.'

**Comment by guillaumearnx** [comment]
Use Node v.14

**Comment by mukesh1234399** [comment]
> Use Node v.14

where it is

**Comment by guillaumearnx** [comment]
> > Use Node v.14
> 
> where it is

U have to install it [here](https://nodejs.org/en/)
