### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'isPlaying' of undefined

### ISSUE THREAD

**Issue by WhiteSkyAngel** [ZerioDev/Music-bot#12]
Hello !
J'ai un petit soucis dans la commande "play" :/

Voici le code + l'erreur : 

![image](https://user-images.githubusercontent.com/44341346/85903875-afaf3b00-b807-11ea-891c-e12529c974a2.png)

![image](https://user-images.githubusercontent.com/44341346/85903879-b50c8580-b807-11ea-815a-d940a7bb19ab.png)

Si quelqu'un aurait la solution, je suis preneur 💯 
Bonne soirée

**Comment by ZerioDev** [comment]
Bonsoir,

Merci de ton report !
Je vais le report à Androz, le créateur du module (discord-player) que le bot utilise. 

Sinon, utilise tu la branche DEV de discord-player et de ce code source ?

Bonne soirée, Zerio 👍

**Comment by WhiteSkyAngel** [comment]
Merci de la réponse !

Non, je viens juste de voir qu'il y avait une branche dev, je vais revoir le code demain et faire des modifs si besoin ^^

**Comment by ZerioDev** [comment]
D'acc, oui effectivement je te conseille d'utiliser la branche dev des deux codes (module/bot).

Pas de problème ^^

**Comment by WhiteSkyAngel** [comment]
Okay, je viens de changer quelques trucs mais j'ai une erreur que j'arrive pas a corriger 

![image](https://user-images.githubusercontent.com/44341346/85922332-c21a8a80-b882-11ea-8e70-34a2983ed5d2.png)

J'ai essayé d'installer (npm install -g ffmpeg-binaries) mais y a pleins d'erreurs :/

**Comment by WhiteSkyAngel** [comment]
My bad :/ 
J'avais pas installé ffmpeg xD

ça fonctionne bien maintenant !
Merci pour l'aide ^^

**Comment by WhiteSkyAngel** [comment]
J'ai un petit soucis, quand je fais la commande "queue", rien ne se passe et il y a aucune erreur dans la console

**Comment by ZerioDev** [comment]
Bonjour !

Quel est le code que vous avez utilisé pour la commande « queue » ?

**Comment by WhiteSkyAngel** [comment]
Celui de la branche dev

**Comment by WhiteSkyAngel** [comment]
![image](https://user-images.githubusercontent.com/44341346/85923078-65ba6980-b888-11ea-880a-65c14c29baa9.png)

J'ai chercher et je me suis dit que c'était peut-être l'embed ?
Est-ce qu'il y a des erreurs ?
