### ISSUE TITLE
How to keep it 24/7 in vc

### ISSUE THREAD

**Issue by lakshya14066** [ZerioDev/Music-bot#121]
Sir please say how do i keep it 24/7 in vc

**Comment by armfxl** [comment]
hey! you could define a channel in the `ready.js` event and have it connect to said channel. this is probably the easiest solution.

```
client.on('ready', () => {

    const channel = client.channels.cache.get('channel-id-here');
    channel.join(channel);
   
});
```

**Comment by Swarwerth** [comment]
If you want to let stay the bot in voice channel 24/7, you are in the good place. In the `index.js` file, you need to replace this:
```js
client.player = new Player(client);
```
by this:
```js
client.player = new Player(client, {leaveOnEnd: false, leaveOnEmpty: false});
```

**Comment by EsoStudio** [comment]
ITs no working :C 
Can you help me?

**Comment by Noman17-tect** [comment]
@EsoStudio 
To keep the bot in the voice channel on queue end & empty voice channel:

In the play.js file where u declare the queue..
Replace 
const queue = await player.createQueue(message.guild, {
            metadata: message.channel
        });

With
const queue = await player.createQueue(message.guild, {
            leaveOnEnd:false,//leaveOnEndCooldown doesnt work anymore
            leaveOnEmptyCooldown: 20000,//or use `leaveOnEmpty:false` to stay in the vc 24/7 , where 20000 is 20 sec
            metadata: message.channel
        });
