### ISSUE TITLE
Cant run npm install

### ISSUE THREAD

**Issue by CloneyInnit** [ZerioDev/Music-bot#124]
Npm install shows this issue:
`$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: @discordjs/opus@0.3.3
npm ERR! node_modules/@discordjs/opus
npm ERR!   @discordjs/opus@"^0.3.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional @discordjs/opus@"^0.5.0" from prism-media@1.2.9
npm ERR! node_modules/prism-media
npm ERR!   prism-media@"^1.2.9" from discord.js@12.5.3
npm ERR!   node_modules/discord.js
npm ERR!     discord.js@"^12.5.1" from the root project
npm ERR!   prism-media@"^1.2.7" from discord-ytdl-core@5.0.2
npm ERR!   node_modules/discord-ytdl-core
npm ERR!     discord-ytdl-core@"^5.0.1" from discord-player@3.4.0
npm ERR!     node_modules/discord-player
npm ERR!       discord-player@"^3.3.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Karol\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Karol\AppData\Local\npm-cache\_logs\2021-04-10T07_09_27_701Z-debug.log
`

running with --force doesn't help

Log file:
[2021-04-10T07_09_27_701Z-debug.log](https://github.com/ZerioDev/Music-bot/files/6289389/2021-04-10T07_09_27_701Z-debug.log)

**Comment by Swarwerth** [comment]
Can you screenshot the folder please?

**Comment by ZerioDev** [comment]
Closed for inactivity !
