### ISSUE TITLE
Error: ffmpeg is not installed

### ISSUE THREAD

**Issue by mariod8** [ZerioDev/Music-bot#126]
SO i'm having this issue. I've already install all modules with _npm install_ and then installed ffmpeg on Linux Mint Xfce. Also tried to install de module with _npm install ffmpeg_ and _npm install ffmpeg-static_.Still getting the error. Bot is running, but not playing anything as if ffmpeg didn't exist at all. Help, ty!

![image](https://user-images.githubusercontent.com/66087392/115116668-1cfcaa00-9f9b-11eb-8a55-68b5858a5b03.png)

**Comment by armfxl** [comment]
Hey!

Have you tried running the bot locally on windows? Try that and then get back here.
Make sure your FFMPEG is working using `ffmpeg -version`

I remember having to install FFMPEG itself on my VPS using these steps.
`1.` Updating package list
```
sudo apt-get update
```
`2.` Installing FFMPEG.
```
sudo apt-get install ffmpeg
```
`3.` Checking FFMPEG version.
```
ffmpeg -version
```

You can also install FFMPEG directly from [this website](https://www.ffmpeg.org/download.html).

**Comment by SMLkaiellis08** [comment]
i did npm install prism-media
and  npm install prism
and then it worked fine for me
