### ISSUE TITLE
filter error

### ISSUE THREAD

**Issue by kdrlegend** [ZerioDev/Music-bot#128]
whenever i try to use any filter bot says- :warning: - Something went wrong ... Error : Error: input stream: write EPIPE

![ijgjjg](https://user-images.githubusercontent.com/70252352/115745865-76a51000-a3b1-11eb-84cf-0b1012039360.PNG)

**Comment by Swarwerth** [comment]
Try to update `discord-player` by typing `npm i discord-player@latest` in the console!

**Comment by ZerioDev** [comment]
Closed for inactivity !
