### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by Gugedo** [ZerioDev/Music-bot#131]
<img width="1680" alt="Schermata 2021-04-29 alle 18 20 51" src="https://user-images.githubusercontent.com/60300082/116584530-bc188e80-a917-11eb-8dad-1a3df3be3454.png">
This is the error and i don't know how to resolve it

**Comment by MaxTechnics** [comment]
Try using `npm i`, or alternatively, manually install the required components
`npm i @discordjs/opus discord-player discord.js ffmpeg-static`
