### ISSUE TITLE
Error: input stream: Status code: 429

### ISSUE THREAD

**Issue by Nubovik01** [ZerioDev/Music-bot#132]
Help! Error 'Error: input stream: Status code: 429'

**Comment by MaxTechnics** [comment]
Did you modify anything? error 429 means a ratelimit, likely something caused a loop somewhere, though you'd need to provide more info for us to help out

**Comment by Swarwerth** [comment]
To avoid it, you can use cookies from YTDL ;))

https://discord-player.js.org/#/docs/main/master/youtube/cookies
