### ISSUE TITLE
Error when playing music

### ISSUE THREAD

**Issue by ghost** [ZerioDev/Music-bot#137]
Getting `:warning: - Something went wrong ... Error : Error: input stream: write EPIPE` randomly while playing music. After getting this error while music is still playing in discord channel music just stops. No errors in console.

**Comment by Swarwerth** [comment]
EPIPE comes from the operating system. To resolve this problem on new versions of `discord-player`, please use Node.js versions 14 LTS. Please go on the [official website of Node.js](https://nodejs.org/en) and install the recommended version.

**On Repl.it, the current version of Node.js is 12, please use an other website or use old versions of `discord-player` (like 3.2.0), you will not have the latest features of Music-bot !*

**Comment by revot334** [comment]
no longer a problem
