### ISSUE TITLE
Please add lyrics command!

### ISSUE THREAD

**Issue by AliAslann** [ZerioDev/Music-bot#138]
Please add lyrics command!

**Comment by Swarwerth** [comment]
You can fetch lyrics with the latest versions of `discord-player` by using `client.player.lyrics()`
I refer you to the [documentation](https://discord-player.js.org/#/docs/main/master/class/Player?scrollTo=lyrics)!

**The command lyrics might not be added in Zerio's Music-bot because there is a lot of issues with using this.*

**Comment by AliAslann** [comment]
> You can fetch lyrics with the latest versions of `discord-player` by using `client.player.lyrics()`
> I refer you to the [documentation](https://discord-player.js.org/#/docs/main/master/class/Player?scrollTo=lyrics)!
> 
> *_The command lyrics might not be added in Zerio's Music-bot because there is a lot of issues with using this._

OMG THANK YOU SO MUCH

**Comment by AliAslann** [comment]
> You can fetch lyrics with the latest versions of `discord-player` by using `client.player.lyrics()`
> I refer you to the [documentation](https://discord-player.js.org/#/docs/main/master/class/Player?scrollTo=lyrics)!
> 
> *_The command lyrics might not be added in Zerio's Music-bot because there is a lot of issues with using this._

Can you send me the correct lyrics.js?

**Comment by Swarwerth** [comment]
> > You can fetch lyrics with the latest versions of `discord-player` by using `client.player.lyrics()`
> > I refer you to the [documentation](https://discord-player.js.org/#/docs/main/master/class/Player?scrollTo=lyrics)!
> > *_The command lyrics might not be added in Zerio's Music-bot because there is a lot of issues with using this._
> 
> Can you send me the correct lyrics.js?

```js
module.exports = {
    name: 'lyrics',
    aliases: [],
    category: 'Music',
    utilisation: '{prefix}lyrics',

    async execute(client, message, args) {
        const queue = client.player.getQueue(message);
        if (!queue && !args[0]) return message.channel.send(`🚫 | You need to provide a track!`);

        message.channel.startTyping();
        const lyrics = await client.player.lyrics(args[0] ? args.join(' ') : client.player.nowPlaying(message).title);
        message.channel.stopTyping();
        
        if (lyrics === null) return message.channel.send(`🚫 | I have not find lyrics for this song! Please retry or search for an other track!`);

        message.channel.send(lyrics.lyrics.length > 1900 ? lyrics.lyrics.substr(0, 1897) + '...' : lyrics.lyrics);
    },
};
```

**Comment by revot334** [comment]
in the todo list!
