### ISSUE TITLE
Music not continue playing after the resume command

### ISSUE THREAD

**Issue by Jam-eng** [ZerioDev/Music-bot#139]
When I use the pause command, it works perfectly fine. Every command works perfectly.
But when I use the resume command, it won't resume the music, instead, the bot plays nothing.

But I'm not sure if it's the error from the script or is it my compiling error ;-;

**Comment by Swarwerth** [comment]
Try this:
```js
module.exports = {
    name: 'resume',
    aliases: [],
    category: 'Music',
    utilisation: '{prefix}resume',

    execute(client, message) {
        if (!message.member.voice.channel) return message.channel.send(`${client.emotes.error} - You're not in a voice channel !`);

        if (message.guild.me.voice.channel && message.member.voice.channel.id !== message.guild.me.voice.channel.id) return message.channel.send(`${client.emotes.error} - You are not in the same voice channel !`);

        if (!client.player.getQueue(message)) return message.channel.send(`${client.emotes.error} - No music currently playing !`);

        if (!client.player.getQueue(message).paused) return message.channel.send(`${client.emotes.error} - The music is already playing !`);

        client.player.resume(message);
        client.player.pause(message);
        client.player.resume(message);

        return message.channel.send(`${client.emotes.success} - Song ${client.player.getQueue(message).playing.title} resumed !`);
    },
};
```

**Comment by ZerioDev** [comment]
Use Node JS 14

**Comment by Jam-eng** [comment]
> Try this:
> 
> ```js
> module.exports = {
>     name: 'resume',
>     aliases: [],
>     category: 'Music',
>     utilisation: '{prefix}resume',
> 
>     execute(client, message) {
>         if (!message.member.voice.channel) return message.channel.send(`${client.emotes.error} - You're not in a voice channel !`);
> 
>         if (message.guild.me.voice.channel && message.member.voice.channel.id !== message.guild.me.voice.channel.id) return message.channel.send(`${client.emotes.error} - You are not in the same voice channel !`);
> 
>         if (!client.player.getQueue(message)) return message.channel.send(`${client.emotes.error} - No music currently playing !`);
> 
>         if (!client.player.getQueue(message).paused) return message.channel.send(`${client.emotes.error} - The music is already playing !`);
> 
>         client.player.resume(message);
>         client.player.pause(message);
>         client.player.resume(message);
> 
>         return message.channel.send(`${client.emotes.success} - Song ${client.player.getQueue(message).playing.title} resumed !`);
>     },
> };
> ```
