### ISSUE TITLE
title is not a property of the discord-player queue.

### ISSUE THREAD

**Issue by Dragonizedpizza** [ZerioDev/Music-bot#144]
In the playlist add event, it says undefined has been added to the queue since title is not a property of playlist.

**Comment by MaxTechnics** [comment]
Can you provide a more complete console log?

**Comment by Dragonizedpizza** [comment]
> Can you provide a more complete console log?

...? You can look at the playlist class, there is no playlist.title.

**Comment by MaxTechnics** [comment]
Oh yeah i see what you mean now. I'll try looking for a possible solution when i get the time to.

**Comment by revot334** [comment]
fixed update bot!
