### ISSUE TITLE
Error when playing music

### ISSUE THREAD

**Issue by JaedonLau** [ZerioDev/Music-bot#146]
When i played the music, the console says that 

(Use `node --trace-warnings ...` to show where the warning was created)
(node:185) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:185) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

This was logged in the console.

**Comment by MaxTechnics** [comment]
Does it mention any line numbers or files? It's hard to track where the rejection happened with the given output.

**Comment by JaedonLau** [comment]
Ye it does track.

**Comment by Teja-12** [comment]
Its Doesnt play any song.
![image](https://user-images.githubusercontent.com/85633624/122665823-33a3c500-d1c7-11eb-828f-06f002d2ca9d.png)

**Comment by MaxTechnics** [comment]
> 
> 
> Its Doesnt play any song.
> ![image](https://user-images.githubusercontent.com/85633624/122665823-33a3c500-d1c7-11eb-828f-06f002d2ca9d.png)

You seem to have a different issue, please open an new issue and provide console errors. Just a screenshot like that doesn't provide enough info

**Comment by revot334** [comment]
fixed in new version please update
