### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by SoundWavez97** [ZerioDev/Music-bot#147]
Hey was wondering if you can add buttons to the music commands

**Comment by MaxTechnics** [comment]
Currently DJS doesn't support this yet. Though i'm sure they're working on it. Same with stage channel support (it is finished, but not released yet). New features on that end will likely take a little longer since we are awaiting a new major version with breaking changes. (DJS 13)

**Comment by revot334** [comment]
done< update bot!
