### ISSUE TITLE
npm install dosent work

### ISSUE THREAD

**Issue by Pingey** [ZerioDev/Music-bot#148]
i followed #131 but it didnt work still
![image](https://user-images.githubusercontent.com/71418083/121971688-b3590c00-cd4f-11eb-9f84-ebc7f4fb2156.png)
i dont know what to do

**Comment by MaxTechnics** [comment]
It reads
> Error: Could not find any Python installation to use
I suggest installing python, not sure which version though

**Comment by revot334** [comment]
no longer a problem
