### ISSUE TITLE
Clear Queue Sans Erreur Console

### ISSUE THREAD

**Issue by LivesRadioDiscord** [ZerioDev/Music-bot#15]
La Commande Clear-Queue s'éxécute, mais ça supprime pas la queue il a aucune erreur dans la console. C'est le même code que dans le fichier commands.

**Comment by ZerioDev** [comment]
Bonjour !

Avez vous fais le test d'ajouter 3/4 musiques. De retaper la commande queue qui devrait afficher les 3/4 musiques à suivre et la musique en cours.

Par la suite réessayer la commande clear-queue. D'après nos tests elle devrait supprimer toutes les musiques a suivre sauf la #1 (la suivante après celle en cours). 

Est ce le cas ? Ou aucune musique ne se supprime ?

Bonne journée à vous.
