### ISSUE TITLE
ffmpeg error

### ISSUE THREAD

**Issue by MX1D** [ZerioDev/Music-bot#151]
it keeps asking me for installing ffmpeg even though i have it installed from the npm command and the windows it self and still same error

**Comment by MaxTechnics** [comment]
try installing globally using `npm install -g ffmpeg-static`

**Comment by CarlosA190** [comment]
I get the same error and I already installed the ffmpeg-static globally, through npm and sudo apt but that error remains, my bot is hosted in a vps

**Comment by revot334** [comment]
install ffmpeg
