### ISSUE TITLE
Error: input stream: Status code: 404

### ISSUE THREAD

**Issue by thomas1329** [ZerioDev/Music-bot#154]
It keeps showing Error: input stream: Status code: 404 - when i ask the bot to play music
What should I do?
![image](https://user-images.githubusercontent.com/82994801/122938591-8faf4a80-d37b-11eb-84fb-4cf3db164ea8.png)

**Comment by guptadevik2003** [comment]
> It keeps showing Error: input stream: Status code: 404 - when i ask the bot to play music
> What should I do?
> ![image](https://user-images.githubusercontent.com/82994801/122938591-8faf4a80-d37b-11eb-84fb-4cf3db164ea8.png)

same

**Comment by MaxTechnics** [comment]
This is apparently a change in youtube's api breaking support for ytdl, a module used to fetch audio from youtube in a lot of projects, including this one. We will have to wait for updates to ytdl and probably some other dependencies before we regain functionality.

**Comment by felid567** [comment]
> This is apparently a change in youtube's api breaking support for ytdl, a module used to fetch audio from youtube in a lot of projects, including this one. We will have to wait for updates to ytdl and probably some other dependencies before we regain functionality.

Will this automatically fix itself or will i have to generate a new Node_modules folder? Also can you tell me when this is updated?

**Comment by tavignesh** [comment]
same error
just encountered today

**Comment by MaxTechnics** [comment]
> > This is apparently a change in youtube's api breaking support for ytdl, a module used to fetch audio from youtube in a lot of projects, including this one. We will have to wait for updates to ytdl and probably some other dependencies before we regain functionality.
> 
> Will this automatically fix itself or will i have to generate a new Node_modules folder? Also can you tell me when this is updated?

You can subscribe to releases for node-ytdl-core. You will have to update your package with npm though. 

I haven't tested this myself yet, but you can manually fix ytdl by modifying a file in the node modules folder
More on that here: https://github.com/fent/node-ytdl-core/pull/938/files

**Comment by felid567** [comment]
> > > This is apparently a change in youtube's api breaking support for ytdl, a module used to fetch audio from youtube in a lot of projects, including this one. We will have to wait for updates to ytdl and probably some other dependencies before we regain functionality.
> > 
> > 
> > Will this automatically fix itself or will i have to generate a new Node_modules folder? Also can you tell me when this is updated?
> 
> You can subscribe to releases for node-ytdl-core. You will have to update your package with npm though.
> 
> I haven't tested this myself yet, but you can manually fix ytdl by modifying a file in the node modules folder
> More on that here: https://github.com/fent/node-ytdl-core/pull/938/files

Do you know which file in which folder ( Sorry im new to this stuff )

**Comment by MaxTechnics** [comment]
That would be 
node_modules/ytdl-core/lib/info.js

**Comment by Nightro-Fx** [comment]
So how can this be fixed

**Comment by MaxTechnics** [comment]
> So how can this be fixed

Please read the entire conversation. The fix is explained. Note that the info.js modification is only a temporary fix, but will be enough to get you started again.
