### ISSUE TITLE
Struggling with error 429 & 404 

### ISSUE THREAD

**Issue by YooItsMaster** [ZerioDev/Music-bot#158]
Each time like literally each time i play music cmd it throws back error 404 or 429 & i even restarted several times but same everytime nothing heard or showed up except those error messages. help plz ?

**Comment by T0TOR** [comment]
look at the other issues and you will find help

**Comment by felid567** [comment]
> Each time like literally each time i play music cmd it throws back error 404 or 429 & i even restarted several times but same everytime nothing heard or showed up except those error messages. help plz ?

https://github.com/ZerioDev/Music-bot/issues/154#issuecomment-866397325 follow this comment and down it helped me fix mine but also the error is fixed. First turn off your bot. Then go to a cmd prompt or terminal and then navigate to the bots folder and then type: 
`npm update ytdl-core`
And that should fix it.
