### ISSUE TITLE
Bug avec les filtres

### ISSUE THREAD

**Issue by Somaxx** [ZerioDev/Music-bot#16]
On peut pas définir ou es l’emplacement de filters.json

**Comment by Androz2091** [comment]
Bonjour, quel est votre problème exactement ? Vous voulez déplacer le fichier json ?

**Comment by Slowzo-Apa** [comment]
Exact

**Comment by Androz2091** [comment]
Il vous faut alors changer le chemin également dans les fichiers suivants:
* https://github.com/ZerioDev/Music-bot/blob/develop/commands/filter.js#L2
* https://github.com/ZerioDev/Music-bot/blob/develop/commands/w-filters.js#L3

**Comment by Slowzo-Apa** [comment]
Je sais, je met bien ./filters.json, mais sa me met : ' Cannot find module ./filters.json' alors que je les bien mit.

**Comment by ZerioDev** [comment]
Bonjour !

Avez vous pensez à modifier avec le nom de votre dossier ?

Exemple `./dossier/fichier.json`. Avez vous essayé de modifier du type `../fichier.json`. 

Votre fichier.json est il dans le même dossier ou non que celui des commandes ?

Bonne journée.
