### ISSUE TITLE
Erreur : LiveVideo

### ISSUE THREAD

**Issue by LeVraiSamy** [ZerioDev/Music-bot#162]
Hello, i have this error when i try to play the lofi girl livestream

**Comment by Johannes7k75** [comment]
what error?

**Comment by LeVraiSamy** [comment]
Error : LiveVideo

**Comment by Johannes7k75** [comment]
you have to enable it if you want to listen to a livestream

**Comment by LeVraiSamy** [comment]
how to activate it ?

**Comment by ZerioDev** [comment]
> Error : LiveVideo

https://discord-player.js.org/#/docs/main/master/class/Player?scrollTo=e-error

**Comment by MaxTechnics** [comment]
https://discord-player.js.org/#/docs/main/master/general/welcome

**Comment by ZerioDev** [comment]
```js
client.player = new Player(client, { enableLive: true });
```

**Comment by LeVraiSamy** [comment]
i add this code in index.js ? which line ?

**Comment by ZerioDev** [comment]
> i add this code in index.js ? which line ?

`index.js`, line 8

![image](https://user-images.githubusercontent.com/43386412/123544632-7e3bb900-d754-11eb-8fca-d54be12e0e2e.png)

**Comment by LeVraiSamy** [comment]
This work, but only 5 seconds, after, the bot say nothing :/

**Comment by Maxence1111** [comment]
Yes after 5 second don't work

**Comment by Johannes7k75** [comment]
for installing discord-player 4.1.4 has fixed the issue
`npm install discord-player@4.1.4`

**Comment by LeVraiSamy** [comment]
yess it's work, thanks you very much dude
