### ISSUE TITLE
Module Error

### ISSUE THREAD

**Issue by modzlobbyz99** [ZerioDev/Music-bot#164]
Error: Error: Cannot find module 'C:\Users\jeri\Desktop\Music-bot-master\node_modules\@discordjs\opus\prebuild\node-v88-napi-v3-win32-x64-unknown-unknown\opus.node'
Require stack:
- C:\Users\jeri\Desktop\Music-bot-master\node_modules\@discordjs\opus\lib\index.js
- C:\Users\jeri\Desktop\Music-bot-master\node_modules\prism-media\src\util\loader.js
- C:\Users\jeri\Desktop\Music-bot-master\node_modules\prism-media\src\opus\Opus.js
- C:\Users\jeri\Desktop\Music-bot-master\node_modules\prism-media\src\opus\index.js
- C:\Users\jeri\Desktop\Music-bot-master\node_modules\prism-media\src\index.js
- C:\Users\jeri\Desktop\Music-bot-master\node_modules\discord.js\src\client\voice\player\BasePlayer.js
- C:\Users\jeri\Desktop\Music-bot-master\node_modules\discord.js\src\client\voice\player\BroadcastAudioPlayer.js
- C:\Users\jeri\Desktop\Music-bot-master\node_modules\discord.js\src\client\voice\VoiceBroadcast.js
- C:\Users\jeri\Desktop\Music-bot-master\node_modules\discord.js\src\client\voice\ClientVoiceManager.js
- C:\Users\jeri\Desktop\Music-bot-master\node_modules\discord.js\src\client\Client.js
- C:\Users\jeri\Desktop\Music-bot-master\node_modules\discord.js\src\index.js
- C:\Users\jeri\Desktop\Music-bot-master\index.js
Error: Cannot find module 'node-opus'
Require stack:
- C:\Users\jeri\Desktop\Music-bot-master\node_modules\prism-media\src\util\loader.js
- C:\Users\jeri\Desktop\Music-bot-master\node_modules\prism-media\src\opus\Opus.js
- C:\Users\jeri\Desktop\Music-bot-master\node_modules\prism-media\src\opus\index.js
- C:\Users\jeri\Desktop\Music-bot-master\node_modules\prism-media\src\index.js
- C:\Users\jeri\Desktop\Music-bot-master\node_modules\discord.js\src\client\voice\player\BasePlayer.js
- C:\Users\jeri\Desktop\Music-bot-master\node_modules\discord.js\src\client\voice\player\BroadcastAudioPlayer.js
- C:\Users\jeri\Desktop\Music-bot-master\node_modules\discord.js\src\client\voice\VoiceBroadcast.js
- C:\Users\jeri\Desktop\Music-bot-master\node_modules\discord.js\src\client\voice\ClientVoiceManager.js
- C:\Users\jeri\Desktop\Music-bot-master\node_modules\discord.js\src\client\Client.js
- C:\Users\jeri\Desktop\Music-bot-master\node_modules\discord.js\src\index.js
- C:\Users\jeri\Desktop\Music-bot-master\index.js
Error: Cannot find module 'opusscript'
Require stack:
- C:\Users\jeri\Desktop\Music-bot-master\node_modules\prism-media\src\util\loader.js
- C:\Users\jeri\Desktop\Music-bot-master\node_modules\prism-media\src\opus\Opus.js
- C:\Users\jeri\Desktop\Music-bot-master\node_modules\prism-media\src\opus\index.js
- C:\Users\jeri\Desktop\Music-bot-master\node_modules\prism-media\src\index.js
- C:\Users\jeri\Desktop\Music-bot-master\node_modules\discord.js\src\client\voice\player\BasePlayer.js
- C:\Users\jeri\Desktop\Music-bot-master\node_modules\discord.js\src\client\voice\player\BroadcastAudioPlayer.js
- C:\Users\jeri\Desktop\Music-bot-master\node_modules\discord.js\src\client\voice\VoiceBroadcast.js
- C:\Users\jeri\Desktop\Music-bot-master\node_modules\discord.js\src\client\voice\ClientVoiceManager.js
- C:\Users\jeri\Desktop\Music-bot-master\node_modules\discord.js\src\client\Client.js
- C:\Users\jeri\Desktop\Music-bot-master\node_modules\discord.js\src\index.js
- C:\Users\jeri\Desktop\Music-bot-master\index.js
    at Object.loader [as require] (C:\Users\jeri\Desktop\Music-bot-master\node_modules\prism-media\src\util\loader.js:12:9)
    at loadOpus (C:\Users\jeri\Desktop\Music-bot-master\node_modules\prism-media\src\opus\Opus.js:17:17)
    at new OpusStream (C:\Users\jeri\Desktop\Music-bot-master\node_modules\prism-media\src\opus\Opus.js:46:10)
    at new Encoder (C:\Users\jeri\Desktop\Music-bot-master\node_modules\prism-media\src\opus\Opus.js:149:5)
    at StreamDownloader (C:\Users\jeri\Desktop\Music-bot-master\node_modules\discord-ytdl-core\index.js:1:1190)
    at C:\Users\jeri\Desktop\Music-bot-master\node_modules\discord-player\src\Player.js:1140:29
    at new Promise (<anonymous>)
    at Player._playYTDLStream (C:\Users\jeri\Desktop\Music-bot-master\node_modules\discord-player\src\Player.js:1121:16)
    at Player._playTrack (C:\Users\jeri\Desktop\Music-bot-master\node_modules\discord-player\src\Player.js:1227:14)
    at C:\Users\jeri\Desktop\Music-bot-master\node_modules\discord-player\src\Player.js:526:22

C:\Users\jeri\Desktop\Music-bot-master>

**Comment by DaSussy** [comment]
did u do 
```cmd
npm i
```

**Comment by modzlobbyz99** [comment]
> did u do
> 
> ```batchfile
> npm i
> ```

yes i already did

**Comment by ZerioDev** [comment]
Install `node-opus` & `opusscript`
