### ISSUE TITLE
Loop spamming 

### ISSUE THREAD

**Issue by ItzDepstRT** [ZerioDev/Music-bot#173]
I have an problem when im playing song and set it to loop it keeps spamming " Now playing songname" can i turn that off?

**Comment by DaSussy** [comment]
try adding this at the **top** of `trackStart.js`

```js
if(client.player.getQueue(message).loopMode) return
```

**Comment by ItzDepstRT** [comment]
Nope... That must be somewhere else nothing happend still spam

**Comment by revot334** [comment]
fixed update discord.js version
