### ISSUE TITLE
Create a userUpdate event

### ISSUE THREAD

**Issue by NaNonnI** [ZerioDev/Music-bot#174]
How can I create a userUpdate command without that it clone itself please?

`module.exports = (client, message) => {
    client.on("userUpdate", function(oldUser, newUser){
        const oldusercache = oldUser
        const newusercache = newUser

        console.log(`user's details (e.g. username) are changed`);
        console.log(`${oldusercache.username}#${oldusercache.discriminator} > ${newusercache.username}#${newusercache.discriminator}`);
            
        let usersdb = client.usersdb.get(oldusercache.id) || [];
        if (usersdb.length > 5) usersdb = usersdb.slice(0, 4)

            usersdb.unshift({
                olduser: oldusercache,
                newuser: newusercache,
                time: Date.now(),
            });
        client.usersdb.set(oldusercache.id, usersdb);
    });
}`

Thx

**Comment by DaSussy** [comment]
bruh this is unrelated to this project, ask in discord.gg/djs

**Comment by revot334** [comment]
comment above, 100% agreed
