### ISSUE TITLE
RAM after disconnect

### ISSUE THREAD

**Issue by Atrexian** [ZerioDev/Music-bot#175]
Hello, everything works fine, but when I left channel and bot left too the RAM is still allocated and wont go down. So after hour my RAM is on 600-800 mb. Can someone help? (When I type !stop its okay - ! is my prefix) Thanks

**Comment by AyeYerMa** [comment]
> Hello, everything works fine, but when I left channel and bot left too the RAM is still allocated and wont go down. So after hour my RAM is on 600-800 mb. Can someone help? (When I type !stop its okay - ! is my prefix) Thanks

Check your task manager, see what is using so much memory and kill the process.

**Comment by DaSussy** [comment]
> Check your task manager, see what is using so much memory and kill the process.

smh

**Comment by revot334** [comment]
discord-player problem

**Comment by revot334** [comment]
looks fixed
