### ISSUE TITLE
TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by JackW25** [ZerioDev/Music-bot#176]
This error occurs whenever I run "npm start" in the bot's terminal
This occurs in the index.js file

(Very new to this stuff, so forgive me if I sound stupid)

**Comment by Johannes7k75** [comment]
do you have two brackets behind it?
()

**Comment by DaSussy** [comment]
did you do any modifications?

**Comment by Androz2091** [comment]
You should use https://github.com/Androz2091/discord-music-bot

**Comment by revot334** [comment]
fixed update bot :)
