### ISSUE TITLE
FFmpeg

### ISSUE THREAD

**Issue by Mage0fDoom** [ZerioDev/Music-bot#178]
(ERROR: FFMPEG is not installed. Install with "npm install ffmpeg-static" or download it here: https://ffmpeg.org/download.html.)
I get this error every time I start the bot and when I use play and the commands work and it joins but it never plays anything and any commands after the first with few exception get "The music is starting... please wait and retry!" and I have tried installing globally and doing audit but it never changes.

**Comment by Valenwe** [comment]
Got the same issue here. Ffmpeg is still in my node modules folder, and everything is up to date.
I think the issue comes from the discord-player module, but I'm not certain

**Comment by Valenwe** [comment]
Okay I did some research on module codes, and it seems that discord-player is using another module called prism-media, and in this prism-media (https://github.com/amishshah/prism-media), there is our error message printed in the console about FFMPEG not being installed.
So I tried downloading it and unzipping in the node modules folder, and it now works! 

The solution is just to manually install that prism-media module.

**Comment by Mage0fDoom** [comment]
Thank you it now works for me as well

**Comment by themixhelp** [comment]
i have same problem today, thanks!

**Comment by revot334** [comment]
looks like it has been resolved!

**Comment by CarlosLeBg** [comment]
Bonne chznce

**Comment by revot334** [comment]
???
