### ISSUE TITLE
Pause and resume commands

### ISSUE THREAD

**Issue by Tommodev-06** [ZerioDev/Music-bot#179]
Hi, first things: nice bot Zerio!

Second thing: I run the bot but the resume command is laggy. Basically, if I do the pause command, it pauses the song perfectly, but if then I do the resume command, the song doesn't start! So to "fix" this issue, I have to do another time the pause command and then the resume command so the songs can start playing again. Is there a way to fix it without running the commands two times?

Thanks!

**Comment by DaSussy** [comment]
add in resume.js:
```js
client.player.resume(message)
client.player.pause(message)
client.player.resume(message)
```

**Comment by Tommins-IT** [comment]
> add in resume.js:
> 
> ```js
> client.player.resume(message)
> client.player.pause(message)
> client.player.resume(message)
> ```

Thanks, it's working perfectly!

**Comment by Xaypanya** [comment]
> add in resume.js:
> 
> ```js
> client.player.resume(message)
> client.player.pause(message)
> client.player.resume(message)
> ```

thank you

**Comment by revot334** [comment]
looks like it has been fixed
