### ISSUE TITLE
Eroor events.js:353       throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by ManZipp** [ZerioDev/Music-bot#184]
the bot suddenly stops and an error appears as shown in the picture

![Uploading gambar.png…]()

**Comment by Shadeys** [comment]
There is not picture that i can see, or it's broken. But could you send the error on here?

**Comment by artificialbutter** [comment]
I'm having the same issue, here's a screenshot 
![image](https://user-images.githubusercontent.com/59352535/135775639-2c6a3d9f-aeb6-41f2-aa1c-7d97cb0eff6b.png)
And here's a [Hastebin](https://hastebin.com/raw/eyotoqezan)

**Comment by revot334** [comment]
fixed with discord-player update
