### ISSUE TITLE
[NO ISSUE] How can I make a voting skip command and stop the spamming caused by the loop mode?

### ISSUE THREAD

**Issue by Rodrolo** [ZerioDev/Music-bot#187]

**Comment by revot334** [comment]
good idea!  will try to implement

**Comment by an2800** [comment]
discord-player not found

**Comment by an2800** [comment]
> 

please help me 
@revot334

**Comment by revot334** [comment]
please run: npm i to fix this also please open a new issue :)

**Comment by revot334** [comment]
i see no point in this issue being open anymore it is added to the to-do list thank you for your suggestion

**Comment by pharos-off** [comment]
up (?)
