### ISSUE TITLE
Crash Filtre Superequalizer

### ISSUE THREAD

**Issue by WhiteSkyAngel** [ZerioDev/Music-bot#19]
Bonjour, quand je lance une musique et que j'y ajoute le filtre Superequalizer, le bot crash instant.

Voici l'erreur : 
![image](https://user-images.githubusercontent.com/44341346/88480910-04ee8180-cf59-11ea-9a87-2d6212b59294.png)

Sauriez-vous m'aidé svp ?

**Comment by Androz2091** [comment]
Bonjour, cela peut venir d'FFMPEG. Certains filters ne fonctionnent pas avec certains OS. Ta version d'FFMPEG est-elle bien la dernière ?

**Comment by WhiteSkyAngel** [comment]
Je crois oui, je vais allé vérifier

**Comment by WhiteSkyAngel** [comment]
![image](https://user-images.githubusercontent.com/44341346/88486928-7f32fc00-cf81-11ea-8f3e-3446097e61c5.png)

**Comment by Androz2091** [comment]
FFMEG se télécharge [ici](https://ffmpeg.org/download.html) et non pas avec NPM.

**Comment by WhiteSkyAngel** [comment]
D'accord merci !

**Comment by ZerioDev** [comment]
Je ferme cette issue en cas de besoin n'hésite pas à en rouvrir une autre 👍
