### ISSUE TITLE
leaveOnEnd 

### ISSUE THREAD

**Issue by Noman17-tect** [ZerioDev/Music-bot#192]
leaveOnEnd not working in new version of music bot, can anyone help?

        const queue = await player.createQueue(message.guild, {
            autoSelfDeaf: false,
            leaveOnEmptyCooldown: 150000,
                leaveOnEndCooldown: 300000,
                leaveOnStopCooldown: 300000,
                    enableLive: true,

            metadata: message.channel
        });

**Comment by lemesherry** [comment]
@Noman17-tect 
Define the discord-player options in config file in main directory, discordPlayer options should be like this.
```
discordPlayer: {}
```
change them to something like this or whatever you want to
```
        discordPlayer: {
            leaveOnEnd: false,
            leaveOnStop: false,
            leaveOnEmpty: true,
            leaveOnEmptyCooldown: 30000,
            autoSelfDeaf: true
        }
```

**Comment by DaSussy** [comment]
> > @Noman17-tect Define the discord-player options in config file in main directory, discordPlayer options should be like this.
> 
> > 
> 
> > ```
> 
> > discordPlayer: {}
> 
> > ```
> 
> > 
> 
> > change them to something like this or whatever you want to
> 
> > 
> 
> > ```
> 
> >         discordPlayer: {
> 
> >             leaveOnEnd: false,
> 
> >             leaveOnStop: false,
> 
> >             leaveOnEmpty: true,
> 
> >             leaveOnEmptyCooldown: 30000,
> 
> >             autoSelfDeaf: true
> 
> >         }
> 
> > ```
> 
> 
> 
> These options don't seem to work unfortunately. Not sure if this is an issue with the bot or discord-player, but these have no effect on behaviour.

its a bot issue

**Comment by revot334** [comment]
fixed
