### ISSUE TITLE
Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.

### ISSUE THREAD

**Issue by mahx890** [ZerioDev/Music-bot#196]
idk why its givving me this error pls help

**Comment by chimnayajith** [comment]
Enable intents in discord developer portal.

**Comment by FelipeHCS** [comment]
Where is it?

**Comment by DaSussy** [comment]
> Where is it?

https://discord.dev

**Comment by FlyingndCoding** [comment]
> > Where is it?
> 
> https://discord.dev

Yup

**Comment by revot334** [comment]
looks like issue has been resolve!
