### ISSUE TITLE
Add command usage!

### ISSUE THREAD

**Issue by Zaid-maker** [ZerioDev/Music-bot#2]
Can you please add command method on how to type the command because it's not working for me everytime I try to play any song it cause error.

**Comment by Zaid-maker** [comment]
Please help me

**Comment by ZerioDev** [comment]
Good evening, can I have the details of the error ?

**Comment by Zaid-maker** [comment]
I have stop using it but I can tell you what's the problem or error.
`unhandledrejectionwarning: object #Object `.  Got this error on every time
I use any command.

**Comment by Androz2091** [comment]
@Zaid-maker when does it happen? Can you check if your youtube API is valid? Can you send the content of the message which cause the error (for example: `!play Alan walker`)? Can you run `npm list`?

**Comment by Zaid-maker** [comment]
Ok can you guys give me 11 to 12 hours because I am in bed now and I will send everything you want.

**Comment by Zaid-maker** [comment]
**The Error when putting the song name.:**
```js
(node:1270) UnhandledPromiseRejectionWarning: #<Object>
(node:1270) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:1270) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Zaid-maker** [comment]
@Androz2091

**Comment by Androz2091** [comment]
I can't access the image. Use something like goopics.net please

**Comment by Zaid-maker** [comment]
Ok

**Comment by Zaid-maker** [comment]
https://cdn.discordapp.com/attachments/666632205803454484/689180311409524824/Capture.PNG

**Comment by Zaid-maker** [comment]
@ZerioDev please help me

**Comment by Androz2091** [comment]
@Zaid-maker that's very weird... Please wait, I'm going to test it on my computer.

**Comment by Zaid-maker** [comment]
ok
