### ISSUE TITLE
Erreur Now-playing

### ISSUE THREAD

**Issue by WhiteSkyAngel** [ZerioDev/Music-bot#20]
Quand on essaie de faire la commande alors que aucune musique n'est jouée, le bot crash et ça met cette erreur : 

![image](https://user-images.githubusercontent.com/44341346/88481566-84ca1b00-cf5c-11ea-904c-27b083f7171c.png)

**Comment by Androz2091** [comment]
C'est bizarre ça, c'est quand tu tapes la commande 1-2 secondes après avoir fait `*play` ou c'est vraiment à un moment ou aucune musique n'allait être jouée ?

**Comment by WhiteSkyAngel** [comment]
Quand aucune musique n'est jouée

**Comment by Androz2091** [comment]
Tu es sur que tu utilises bien la dernière version du bot ? La commande est `np`.

**Comment by WhiteSkyAngel** [comment]
Bonsoir, désolé de la réponse tardive...

Mais je crois que l'erreur vient du faite que quand un utilisateur exécute la commande alors qu'il est dans un salon et aucune musique n'est jouée, la ligne "if(!client.player.isPlaying(message.guild.id)) return message.channel.send(nomusicplayedEmbed);" ne fonctionne pas :/

**Comment by ZerioDev** [comment]
Issue inactive, je ferme celle-ci. Si besoin, il y a la possibilité d'en rouvrir une 😉
