### ISSUE TITLE
Leaving after 2 seconds into track

### ISSUE THREAD

**Issue by LegalSmeagol** [ZerioDev/Music-bot#205]
The issue [here](https://github.com/ZerioDev/Music-bot/pull/199) related to the leaving after 2 seconds into a track still persists despite the recent commit.

I have the following options set:

`discordPlayer: {
            leaveOnEnd: false,
            leaveOnStop: true,
            leaveOnEmpty: true,
            leaveOnEmptyCooldown: 1000,
            autoSelfDeaf: true,
            ytdlOptions: {
                quality: 'highestaudio',
                highWaterMark: 1 << 25
            }
        }`

No errors in console.

**Comment by LegalSmeagol** [comment]
> There might be some error in the console check that

I wish there were errors in console, but nothing appears in console when it happens.

**Comment by Jacob439** [comment]
The same thing is happening to me for certain tracks. One example is "trust me I'm an engineer". This fails during search and when the link is played. https://youtu.be/rp8hvyjZWHs

**Comment by Arburich** [comment]
add to `play.js`

```javascript
const queue = await player.createQueue(message.guild, {
			ytdlOptions: {
				quality: "highest",
				filter: "audioonly",
				highWaterMark: 1 << 25,
				dlChunkSize: 0,
			},
			metadata: message.channel
		});```

**Comment by tstern27** [comment]
@Arburich Thank you so much! 

I was having the same issue where youtube links would play only play audio for a second and then cut out. 

I can confirm the above solutions resolved my problem as well.

**Comment by revot334** [comment]
fixed in new discord player version
