### ISSUE TITLE
Cannot play a resource that has already ended.

### ISSUE THREAD

**Issue by Ansh-Sonkusare** [ZerioDev/Music-bot#207]
Error emitted from the queue Status code: 403
Error emitted from the connection [PlayerError] Cannot play a resource that has already ended.
 Error emitted from the queue [DestroyedQueue] Cannot use destroyed queue 

This happens mostly these days on specific songs 
it might be the discord-player's issue

**Comment by Ayinaki** [comment]
Same issue here, Any fixed been found?

**Comment by Zyztem** [comment]
Same issue

**Comment by LouieBigBoi** [comment]
Same Issue Here

**Comment by Zyztem** [comment]
A new config has been found. and fixes the issue
```js
 ytdlOptions: {
                filter: "audioonly",
                opusEncoded: "true",
                quality: 'highestaudio',
                highWaterMark: 1 << 30, // DONT TOUCH
            }```
the highWaterMark needs to be adjusted from 25 to 30
