### ISSUE TITLE
Question Lancement Musique

### ISSUE THREAD

**Issue by WhiteSkyAngel** [ZerioDev/Music-bot#21]
Hey !
Quand je lance une musique, tout va bien mais un petit message apparaît dans la console et je sais pas trop comment l'enlever... 

Le voici: 
![image](https://user-images.githubusercontent.com/44341346/88487092-860e3e80-cf82-11ea-98ec-13e545638bc5.png)

Vous avez une solution ?

**Comment by ZerioDev** [comment]
Hey hey ! 

C'est censé être patch :
![image](https://user-images.githubusercontent.com/43386412/89946798-c37df780-dc23-11ea-9869-5554561be211.png)

**Comment by WhiteSkyAngel** [comment]
Ah ok mais pourtant dans la branche dev ou master il y a eu aucune MAJ... les dernières dates d'il y a 2 mois :/
