### ISSUE TITLE
Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted

### ISSUE THREAD

**Issue by Itzzz-Malik** [ZerioDev/Music-bot#220]
But my bot verified , i'm not turn on ? help me

**Comment by DaSussy** [comment]
smh, enable the intents in the bot section of your bot app (https://discord.dev)

**Comment by dragonfirefox** [comment]
You're using message intent which is now privileged and requires to grant, you didn't got the intent yet, first got it by applying to developers portal then you're able to use this code since it uses message content.

**Comment by revot334** [comment]
@Itzzz-Malik  looks like these other people have helped
