### ISSUE TITLE
Trackstart 

### ISSUE THREAD

**Issue by vanna-code** [ZerioDev/Music-bot#229]
why Trackstart have `added in the queue` ?

how to delete ?

**Comment by BlobDeveloper** [comment]
@vanna-code could you describe your problem in more detail?
The best thing to do is to connect to the ZerioDev official discord server, we will help you there.
https://discord.gg/dhsR5M76WR

**Comment by revot334** [comment]
@vanna-code  has your issue been resoled yet ? if not this is a very easy problem to solve you need to go into: Music-bot/src/events.js then delete line 14 - 16
