### ISSUE TITLE
Double Commands

### ISSUE THREAD

**Issue by Dino186** [ZerioDev/Music-bot#236]
Hey, the Bot works fine and it's really good, but the Commands are *2. Any solution to it for me?

**Comment by revot334** [comment]
can you send me a picture of this problem to help you better

**Comment by Dino186** [comment]
> can you send me a picture of this problem to help you better

![double commands](https://user-images.githubusercontent.com/109483378/184428198-207093ad-8545-4eb2-971d-ed9fc08fcb39.png)
This is what it looks like

**Comment by revot334** [comment]
did you have them set a local commands and then global commands ?

**Comment by Dino186** [comment]
> did you have them set a local commands and then global commands ?

local

**Comment by revot334** [comment]
can you join our discord so i can help you better https://discord.com/invite/5cGSYV8ZZj

**Comment by Dino186** [comment]
> can you join our discord so i can help you better https://discord.com/invite/5cGSYV8ZZj

sure
