### ISSUE TITLE
Bot Crashes If You Use Controller Command Without Manage Channel Permissions

### ISSUE THREAD

**Issue by AnaheimDucks16** [ZerioDev/Music-bot#239]
The bot will crash if someone uses the controller command when they don't have manage channel permission.

**Comment by BlobDeveloper** [comment]
Have you edited anything in the code?

**Comment by AnaheimDucks16** [comment]
No

**Comment by AnaheimDucks16** [comment]
@revot334 @ZerioDev You may want to check this out

**Comment by revot334** [comment]
looking in to it

**Comment by revot334** [comment]
> @revot334 @ZerioDev You may want to check this out

do you mind sending me the error

**Comment by revot334** [comment]
fixed update bot please

**Comment by AnaheimDucks16** [comment]
Thanks!

**Comment by revot334** [comment]
any time
