### ISSUE TITLE
[Feature suggestion] Lyrics

### ISSUE THREAD

**Issue by pendragons-code** [ZerioDev/Music-bot#242]
I know that the lyrics command is in progress, but I would like to suggest an API:
some-random-api.ml

while I understand that the command is in development, I think that this is one of the best apis most people can use!

At the same time, I think that whatever API you use, you would most likely run into a common issue, word limits on an embed

While you may be able to add multiple fields and titles (`.addfields()`), there is a limit of 25 fields. While that alone is very difficult for a song to fill up, it is still possible and the embeds would be really big, annoying people. Therefor, it would seem beneficial to send the embed or link into the direct message of the person who requested it. (or at least ask if they want it in the channel or the dms)

Thank you!

**Comment by pendragons-code** [comment]
The giant blobs of text and embeds annoying people is a problem that is more problematic for users on mobile.

**Comment by revot334** [comment]
only if there where pages 🤔

**Comment by pendragons-code** [comment]
https://some-random-api.ml/endpoints
https://some-random-api.ml/lyrics

Is this what you meant? Also it seems to lead to genius lyrics. It works
pretty well, especially since the systems also seems to account for typos.

**Comment by pendragons-code** [comment]
> only if there where pages thinking

should i close this?

also if you mean pages, just take the contents and divide accordingly.

So let's say the chorus:

"bananananananananananannanananana"


so we can cut the embed by verse, chorus, bridge and whatever since if i am not wrong the thing actually splits it up like that. In an event that it does not, just divide the number of words by the maximum number of words per embed and send that many embeds (adjust for the remainder)

**Comment by revot334** [comment]
pages inside discord 🤔

**Comment by pendragons-code** [comment]
> pages inside discord thinking

wdym pages inside discord

**Comment by RappyTV** [comment]
just put it into the description (character limit is 4096 there)

**Comment by pendragons-code** [comment]
i did say that before and 4096 ain't long enough for some songs.

**Comment by revot334** [comment]
its comming

**Comment by revot334** [comment]
check out the beta! if you want it now if you prefer to wait v8 will be out in 4 days https://github.com/ZerioDev/Music-bot/tree/beta-(Bugs-are-expected)
