### ISSUE TITLE
Prefixo

### ISSUE THREAD

**Issue by eumax39** [ZerioDev/Music-bot#244]
Gostaria de saber como posso mudar o prefixo do bot?
O bot só funciona apenas com o link da musica ou ele também consegue reproduzir a musica apenas com o nome da musica?

**Comment by Johannes7k75** [comment]
The bot is slash based so you cant change the prefix.
And you can just use `/play SONGNAME` no need for just the link

**Comment by Johannes7k75** [comment]
Is your issue resolved?
