### ISSUE TITLE
How to chang butten word 

### ISSUE THREAD

**Issue by goldball1105** [ZerioDev/Music-bot#247]
So I mean the butten word that on discord, I found many file but I still can't find the file that can change to word on butten
(if you don't know what am I talking about look at this picture <https://imgur.com/5MNJn1b>)

**Comment by pendragons-code** [comment]
based on my quick glance, you just need to rename the file and call it accordingly.

**Comment by xTz11** [comment]
or edit the files in   ../src/events.js  line 19,24,..  beetween ' ..'

**Comment by xTz11** [comment]
Edit the events.js file found in src, the lines are those starting with .setlabel ..
Ex: .setLabel('Back')

**Comment by goldball1105** [comment]
thx you guys so much!!!
