### ISSUE TITLE
Options do not work with unlinked music

### ISSUE THREAD

**Issue by Alaixs** [ZerioDev/Music-bot#257]
When I type a music without links ("/play Mickael Jackson Thriller" for example) the options pauses, resume, clear, stop, loop... don't work, the bot doesn't detect any music playing ( No music currently playing @Alex... try again ? ❌ ) 

Very good work otherwise 👍 !

**Comment by NotAryaaa** [comment]
Its your hosting problem, try switching it

**Comment by revot334** [comment]
might be your host... also might be the bot please wait for new version if it still dose not work then open a new issues
