### ISSUE TITLE
** HUGE PROBLEM **:song stops automatically

### ISSUE THREAD

**Issue by Satyaki34** [ZerioDev/Music-bot#259]
# HUGE PROBLEM
the /play command works fine...the bot connect to the voice channel and started playing but suddenly it stops playing in middle of song...and leaves automatically...all my friends get the same problem..please fix it ...its huge problem...if i music bot can't play music its not worth it

**Comment by iGameCreep** [comment]
Hello !
Can you try with this one ? It is using the latest version of the package discord-player, should have less bugs.
https://github.com/iGameCreep/Music-bot

**Comment by gmed2b** [comment]
Hey, I wanted to try yours to fix that same problem but now, when i play a song, the bot instantly disconnect :/

**Comment by revot334** [comment]
should be fixed in new version coming out in a few days :)
