### ISSUE TITLE
The music bot still stops after that disconects 

### ISSUE THREAD

**Issue by Ticst** [ZerioDev/Music-bot#260]

**Comment by iGameCreep** [comment]
Hello !
Can you try with this one ? It is using the latest version of the package discord-player, should have less bugs.
https://github.com/iGameCreep/Music-bot

**Comment by muhitrhn** [comment]
Yo @iGameCreep I installed the code from the repo you provided. but can't play music. When I do /`play`, it just shows the song has started then no music and this error `Error emitted from the queue Cannot play a resource that has already ended.`

**Comment by matt-t-jones** [comment]
Thanks for your work on this @iGameCreep ! I was about to go through and update it but you took care of it 👍

**Comment by jodic97** [comment]
> Yo @iGameCreep I installed the code from the repo you provided. but can't play music. When I do /`play`, it just shows the song has started then no music and this error `Error emitted from the queue Cannot play a resource that has already ended.` in logs

Hey! Same error happens but with Error emitted from the queue Cannot read properties of undefined (reading 'name').  I think it's either @discordjs/voice issue probably. I tried rerolling both discord-player and @discordjs, along with @discordjs/voice, but I think it's from the voice package, that both the new repository uses and discord-player module. The fix could be either found in this [issue](https://github.com/discordjs/discord.js/issues/9185#issuecomment-1452514375) or this [other issue](https://github.com/BigChicChicken/NW_TimerBot/issues/5#issuecomment-1472991404). Let me know which one works better, but I think it's on the developer's end and we are expecting a fix.

**Comment by itsjustyryr** [comment]
> > Yo @iGameCreep I installed the code from the repo you provided. but can't play music. When I do /`play`, it just shows the song has started then no music and this error `Error emitted from the queue Cannot play a resource that has already ended.` in logs
> 
> 
> 
> Hey! Same error happens but with Error emitted from the queue Cannot read properties of undefined (reading 'name').  I think it's either @discordjs/voice issue probably. I tried rerolling both discord-player and @discordjs, along with @discordjs/voice, but I think it's from the voice package, that both the new repository uses and discord-player module. The fix could be either found in this [issue](https://github.com/discordjs/discord.js/issues/9185#issuecomment-1452514375) or this [other issue](https://github.com/BigChicChicken/NW_TimerBot/issues/5#issuecomment-1472991404). Let me know which one works better, but I think it's on the developer's end and we are expecting a workaround or something.
> 
> 

I agree here with @jodic97 , try changing the code from the original repository with the new repo, and keep troubleshooting. I might launch a unworked, still problematic version (skip, queue and embeds are not creating) but the best fix for this is disconnecting the bot. Filter and volume commands are working perfectly!
