### ISSUE TITLE
Error when playing a song

### ISSUE THREAD

**Issue by itsjustyryr** [ZerioDev/Music-bot#264]
Even though the bot is in the beta stage, I've took my time to find a issue: 

> const error = new Error("Could not extract stream for this track");
                          ^
Error: Could not extract stream for this track
    at GuildQueuePlayerNode.play (C:\Users\Users\Desktop\bot\node_modules\discord-player\dist\index.js:985:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.execute (C:\Users\User\Desktop\bot\commands\music\play.js:58:33)

Versions:

Node.js v18.12.1
discord-player v6.1.1

**Comment by CaptSpider4** [comment]
skipOnNoStream: true

this option in queue creation should fix this issue 

Note: It doesn't make bot play song it will just not throw this error

This error is possibly due to play age restricted or region restricted songs

**Comment by itsjustyryr** [comment]
> `skipOnNoStream: true`
> 
> this option in queue creation should fix this issue
> 
> Note: It doesn't make bot play song it will just not throw this error
> 
> This error is possibly due to play age restricted or region restricted songs this could also be due to [Androz2091/discord-player#1705](https://github.com/Androz2091/discord-player/issues/1705)

I've actually pasted a Spotify link in the command bar of the bot when using /play.
The skipOnNoStream: true has to be added in config, even though it does not play the song?
Maybe it should be replaced with play-dl, which means I might have to install play-dl, force it to use play-dl and rewrite the code. I might either launch it tommorow or another day

**Comment by skdhg** [comment]
You don't have to rewrite your code, just add this environment variable `DP_FORCE_YTDL_MOD="play-dl"` in your .env file. Make sure you have play-dl installed though. You can also try using `@distube/ytdl-core` (`DP_FORCE_YTDL_MOD="@distube/ytdl-core"` & `npm i @distube/ytdl-core`)

**Comment by itsjustyryr** [comment]
> You don't have to rewrite your code, just add this environment variable `DP_FORCE_YTDL_MOD="play-dl"` in your .env file. Make sure you have play-dl installed though. You can also try using `@distube/ytdl-core` (`DP_FORCE_YTDL_MOD="@distube/ytdl-core"` & `npm i @distube/ytdl-core`)

Where is the .env file? Is it found in the main page? The config file? The modules folder? I will install both

**Comment by revot334** [comment]
fixed in beta

**Comment by itsjustyryr** [comment]
> fixed in beta

Nice!! I will look into it today
