### ISSUE TITLE
Not playing any songs

### ISSUE THREAD

**Issue by Alphaegen** [ZerioDev/Music-bot#266]
The bot does join, but it doesn't play anything and the queue is immediately cleared. The bot is deafened, but that might be normal. I've got ffmpeg installed:
<img width="650" alt="image" src="https://user-images.githubusercontent.com/45634800/230638471-82a4d38a-9335-48d3-aa07-e433e9616c4a.png">

My node version is 16.20.0.

**Comment by Alphaegen** [comment]
There are no errors:
<img width="390" alt="image" src="https://user-images.githubusercontent.com/45634800/230638628-d69a8567-16ba-4bb6-920f-672aac8e8c46.png">

**Comment by Alphaegen** [comment]
What permissions does the bot need?

**Comment by Alphaegen** [comment]
This is the error if I try to run it using the beta branch:
<img width="650" alt="image" src="https://user-images.githubusercontent.com/45634800/230641484-037bd9eb-16ca-47e8-8d07-ba162858aeb1.png">

**Comment by skdhg** [comment]
> This is the error if I try to run it using the beta branch: <img alt="image" width="650" src="https://user-images.githubusercontent.com/45634800/230641484-037bd9eb-16ca-47e8-8d07-ba162858aeb1.png">

https://github.com/Androz2091/discord-player/issues/1705

**Comment by Alphaegen** [comment]
<img width="704" alt="image" src="https://user-images.githubusercontent.com/45634800/230674901-47a3eadf-3dc4-4589-8933-187ec2dfd1c9.png">

**Comment by ShambaC** [comment]
Uninstall ffmpeg static and remove it from node-modules
https://github.com/Androz2091/discord-player/issues/1639#issuecomment-1477466885
https://github.com/Androz2091/discord-player/issues/1639#issuecomment-1477793093

**Comment by Alphaegen** [comment]
Removed ffmpeg-static from package.json, removed package-lock.json and reinstalled node modules. The node_modules folder doesn't contain ffmpeg-static anymore, but it's still doing the same. No music and the queue instantly gets cleared. Any way to debug this the way the person did in the thread you sent above?

**Comment by skdhg** [comment]
> Removed ffmpeg-static from package.json, removed package-lock.json and reinstalled node modules. The node_modules folder doesn't contain ffmpeg-static anymore, but it's still doing the same. No music and the queue instantly gets cleared. Any way to debug this the way the person did in the thread you sent above?

what is your discord-player version?

**Comment by Alphaegen** [comment]
I've got these versions:
<img width="339" alt="image" src="https://user-images.githubusercontent.com/45634800/230773364-fe8e5c0f-97a5-44c8-84fd-afb2240b7f8c.png">

**Comment by Alphaegen** [comment]
Someone said missing these could be the problem, but I've got them enabled:
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/45634800/230773812-9f54056c-a03d-416d-a5f5-00d86743ea05.png">

**Comment by itsjustyryr** [comment]
Hey buddy! Try removing ffmpeg-static and run `sudo snap install ffmpeg` on the /* folder. This was my fix, try doing the same thing. It should work.

**Comment by skdhg** [comment]
> I've got these versions: <img alt="image" width="339" src="https://user-images.githubusercontent.com/45634800/230773364-fe8e5c0f-97a5-44c8-84fd-afb2240b7f8c.png">

could you show me your `package.json`?

**Comment by Alphaegen** [comment]
<img width="644" alt="image" src="https://user-images.githubusercontent.com/45634800/230773943-29595db5-2868-4fcd-a44e-a3e3a3b660d3.png">

**Comment by skdhg** [comment]
You are missing `@discord-player/extractor` package

**Comment by Alphaegen** [comment]
> Hey buddy! Try removing ffmpeg-static and run `sudo snap install ffmpeg` on the /* folder. This was my fix, try doing the same thing. It should work.

I'm afraid I've already uninstalled ffmpeg-static and installed ffmpeg with `sudo apt install ffmpeg`.

**Comment by itsjustyryr** [comment]
> > Hey buddy! Try removing ffmpeg-static and run `sudo snap install ffmpeg` on the /* folder. This was my fix, try doing the same thing. It should work.
> 
> I'm afraid I've already uninstalled ffmpeg-static and installed ffmpeg with `sudo apt install ffmpeg`.

Same here! When adding a filter to the song, the songs stops playing.

**Comment by skdhg** [comment]
> Removed ffmpeg-static from package.json, removed package-lock.json and reinstalled node modules. The node_modules folder doesn't contain ffmpeg-static anymore, but it's still doing the same. No music and the queue instantly gets cleared. Any way to debug this the way the person did in the thread you sent above?

The debug logs from the mentioned thread is from discord-player v6. v5 logs are not that great/useful. Plus all the versions below 6.0.0 are deprecated. Could you try the `beta` branch instead?

**Comment by Alphaegen** [comment]
I'm now on the beta branch and am now running into the following error:
```/home/server/ngmusicbot/node_modules/discord-player/dist/index.js:985
        const error = new Error("Could not extract stream for this track");
                      ^

Error: Could not extract stream for this track
    at GuildQueuePlayerNode.play (/home/server/ngmusicbot/node_modules/discord-player/dist/index.js:985:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.execute (/home/server/ngmusicbot/commands/music/play.js:59:33)```

Should I remove ffmpeg-static from package.json again to fix this?

**Comment by itsjustyryr** [comment]
> I'm now on the beta branch and am now running into the following error:
> 
> ```
>         const error = new Error("Could not extract stream for this track");
>                       ^
> 
> Error: Could not extract stream for this track
>     at GuildQueuePlayerNode.play (/home/server/ngmusicbot/node_modules/discord-player/dist/index.js:985:23)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async Object.execute (/home/server/ngmusicbot/commands/music/play.js:59:33)```


I've removed ffmpeg-static from node_modules but not from package.json file.

**Comment by Alphaegen** [comment]
Removing `ffmpeg-static` doesn't seem to fix this problem.

**Comment by itsjustyryr** [comment]
> Removing `ffmpeg-static` doesn't seem to fix this problem.

That's odd. Here, at my end, it worked..

**Comment by Alphaegen** [comment]
Completely removing `package-lock.json` and `node_modules`, then reinstalling everything with `yarn` seems to have fixed it. The `lyrics` button does seem to fail with this error, but everything else works.

Error for lyrics:
`node:events:491
      throw er; // Unhandled 'error' event
      ^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at SongsClient.<anonymous> (/home/server/ngmusicbot/node_modules/genius-lyrics/dist/songs/client.js:47:37)
    at Generator.next (<anonymous>)
    at fulfilled (/home/server/ngmusicbot/node_modules/genius-lyrics/dist/songs/client.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Emitted 'error' event on Client instance at:
    at emitUnhandledRejectionOrErr (node:events:394:10)
    at processTicksAndRejections (node:internal/process/task_queues:85:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by itsjustyryr** [comment]
> Completely removing `package-lock.json` and `node_modules`, then reinstalling everything with `yarn` seems to have fixed it. The `lyrics` button does seem to fail with this error, but everything else works.
> 
> Error for lyrics:
> 
> ```
>       throw er; // Unhandled 'error' event
>       ^
> 
> SyntaxError: Unexpected token < in JSON at position 0
>     at JSON.parse (<anonymous>)
>     at SongsClient.<anonymous> (/home/server/ngmusicbot/node_modules/genius-lyrics/dist/songs/client.js:47:37)
>     at Generator.next (<anonymous>)
>     at fulfilled (/home/server/ngmusicbot/node_modules/genius-lyrics/dist/songs/client.js:5:58)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> Emitted 'error' event on Client instance at:
>     at emitUnhandledRejectionOrErr (node:events:394:10)
>     at processTicksAndRejections (node:internal/process/task_queues:85:21)
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.```
> ```

lyrics command isn't fully launched yet. I suggest not using it, as the lyrics that get looked up get searched on the genius website, a website that provides lyrics for your wished track. Apparently, lyrics work here but that is odd. You shouldn't have removed package-lock file, you should've just left it there. Remove node_modules folder, along with yarn.lock file, add back the package-lock.json file, then use `yarn install` again.

**Comment by Alphaegen** [comment]
> 

The `package-lock` file only gets generated when running `npm install`. It's not a file that's kept within the Git repo. Is there a specific archive I can download with the beta branch + package-lock I've missed?

**Comment by itsjustyryr** [comment]
> > 
> 
> The `package-lock` file only gets generated when running `npm install`. It's not a file that's kept within the Git repo. Is there a specific archive I can download with the beta branch + package-lock I've missed?

I am sorry. Yes, there is no package-lock. only if you run `npm install`, I am kind of unfocused. Have you removed the node_modules and used `yarn install`?

**Comment by Alphaegen** [comment]
Yes, I've done exactly that 👍 The music plays now, but the lyrics function still gives an error.

**Comment by itsjustyryr** [comment]
> Yes, I've done exactly that 👍 The music plays now, but the lyrics function still gives an error.

That is odd. Mine is fully functional.. Make sure you are on the latest update of the branch or try downloading the lyrics file from the beta branch, from music subfolder of the commands folder from the main folder and from buttons subfolder of the src folder from the branch.

**Comment by skdhg** [comment]
> Yes, I've done exactly that 👍 The music plays now, but the lyrics function still gives an error.

have you tried bumping genius-lyrics?

**Comment by Alphaegen** [comment]
Haven't but I've simply removed the button locally for now. It's not something we're planning on using soon. @skdhg I am wondering tho, why hasn't the `ffmpeg-static` package been removed from the package.json if it doesn't work?

**Comment by Alphaegen** [comment]
This is fixed for now. I'm closing this issue.
