### ISSUE TITLE
Could not extract stream for this track

### ISSUE THREAD

**Issue by originalaidn** [ZerioDev/Music-bot#274]
/home/container/node_modules/discord-player/dist/index.js:985
        const error = new Error("Could not extract stream for this track");
                      ^
Error: Could not extract stream for this track
    at GuildQueuePlayerNode.play (/home/container/node_modules/discord-player/dist/index.js:985:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.execute (/home/container/commands/music/play.js:59:33)
Node.js v17.9.1

**Comment by Alphaegen** [comment]
On which branch are you?

**Comment by Alphaegen** [comment]
Could you try running `DP_FORCE_YTDL_MOD='play-dl' yarn start` or `DP_FORCE_YTDL_MOD='play-dl' npm start` for me? Depending on which package manager you're using of course. Then try playing a song again.

As a sidenote, have you installed `ffmpeg` as a package of your system? Which version is it? (you can check by running `ffmpeg`)

**Comment by originalaidn** [comment]
I couldn't run these commands, because my bot is running in a container (the host uses containers to NODEJS, PYTHON, DOTNET 5 & 6 bots), and I can't run commands in console.


I used this (https://github.com/iGameCreep/Music-bot) version, but since Saturday I didn't get error but also the music not started

**Comment by Darthwayne** [comment]
I have the same issue. Bot works fine on desktop, but when I put it into a free hosting service, it auto updates packages, adding yt-dlcore, removing another. Error becomes 'could not extract stream'. Hopefully the calls to the unneeded dependencies can be removed whatever they specifically are.

**Comment by originalaidn** [comment]
my problem solved, but idk how
