### ISSUE TITLE
The Bot keeps Stopping after 30seconds With Music Playback

### ISSUE THREAD

**Issue by BizegamingTV** [ZerioDev/Music-bot#275]
Hello There Develoapers or Community Members i have and issue which is that the bot keeps stopping after 30 seconds there is no Log No Error and No Fix it happens on YT and Spotify i really need to fix it can anyone help me out Please

**Comment by BananinBanano** [comment]
I had the same issue, just move to beta version, it works well, you just need to install yarn

**Comment by BizegamingTV** [comment]
ill try that thankyou for you help

**Comment by BizegamingTV** [comment]
So Turns out yarn is installed so i guess it still not working

**Comment by BananinBanano** [comment]
You have yarn, but do you have beta version installed? Or just yarn installed?

**Comment by BizegamingTV** [comment]
what type of beta there is only a release and i only have yarn and nodejs installed not any

**Comment by Etwenn** [comment]
same bug here, how can we get the beta ?

**Comment by BizegamingTV** [comment]
i realised i didnt have ffmpeg installed but still that did not help

**Comment by BananinBanano** [comment]
Just go to "select branch" and choose beta

**Comment by BizegamingTV** [comment]
ok ill try that

**Comment by BizegamingTV** [comment]
im using beta and still that didnt fix the Problem

**Comment by BizegamingTV** [comment]
So turns out  i get a Error when i try to Launch the beta with node main.js 

   TypeError: Cannot read properties of undefined (reading 'includes')
    at /home/Discordbots/Music-bot/node_modules/discord-player/dist/index.js:2289:29
    at Object.<anonymous> (/home/Discordbots/Music-bot/node_modules/discord-player/dist/index.js:2295:3)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/home/Discordbots/Music-bot/main.js:1:20)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)

**Comment by BizegamingTV** [comment]
i fixed it its The main Branch and its broken solution use beta and Reconfigure your Bot Thankyou Everyone for your Help if you need a helping Hand add me on Discord otherwise join my server https://discord.gg/gHWDvNVF52 have a good day week what ever or anything else Stay active and Creative

**Comment by BananinBanano** [comment]
I'm glad you could solve your problem
