### ISSUE TITLE
The bot won't play music

### ISSUE THREAD

**Issue by G-IDEON** [ZerioDev/Music-bot#276]
I start the bot, there're no errors, everything is ok. When I enter the play command and specify the music, the bot writes what it adds to the queue, connects to the channel, and the text is immediately sent: No more songs in the queue! 
As a result, the music doesn't turn on.  There're no errors in the console. I noticed that it periodically starts the song, but most often it doesn't work with the answer that I indicated earlier. Let's say if I enter the name of the track or a link to it, then it doesn't play it, as described above, but if I write a couple of random letters, then it turns on some random music and works

**Comment by itsjustyryr** [comment]
Hi! Use the beta branch, as the main one is broken.
