### ISSUE TITLE
Bot disconnect when playing music and no error

### ISSUE THREAD

**Issue by KoyumeFR** [ZerioDev/Music-bot#281]
when i play a music the music are playing for few seconds and the music stop instantly et it say this : 
![image](https://user-images.githubusercontent.com/108196444/236823281-766175a0-b736-4901-a7c0-362a19b64cb5.png)

**Comment by Fluffik3666** [comment]
You have a low bandwidth. Music bots require A LOT of it. Make sure to not run this on Replit (like I did) and run this ffmpeg installed.

**Comment by pendragons-code** [comment]
no this is related to the fact that there were some changes made to how vcs work

**Comment by pendragons-code** [comment]
https://github.com/ZerioDev/Music-bot/issues/283

upgrading will fix it
