### ISSUE TITLE
disconnect when playing music after few seconds and no error

### ISSUE THREAD

**Issue by Gamerdamor** [ZerioDev/Music-bot#283]
When I use the /play command and let it play the song, after 50 seconds or 1 minute or so, the music stops and it disconnects from the channel and I get the message "I have been manually moved from the channel" as if someone did it removed, and it should be noted that it is not a problem of bandwidth or my computer, since I am doing it from a paid host and previously I did it from my PC and the same thing also happened

![image](https://github.com/ZerioDev/Music-bot/assets/78004081/712bd761-2120-4e14-936a-48061554b531)

**Comment by pendragons-code** [comment]
[This is because of a change made to discord, they set a limit to how long audio](https://github.com/Androz2091/discord-player/issues/1630)
