### ISSUE TITLE
[Bug with fix available] No extractors fix.

### ISSUE THREAD

**Issue by pendragons-code** [ZerioDev/Music-bot#284]
```
const { Player } = require('discord-player');
const Genius = require("genius-lyrics");
const { Client, GatewayIntentBits } = require('discord.js');
const { YouTubeExtractor } = require("@discord-player/extractor");
global.client = new Client({
    intents: [
        GatewayIntentBits.Guilds,
        GatewayIntentBits.GuildMembers,
        GatewayIntentBits.GuildMessages,
        GatewayIntentBits.GuildVoiceStates,
        GatewayIntentBits.MessageContent
    ],
    disableMentions: 'everyone',
});

client.config = require('./config');

global.player = new Player(client, client.config.opt.discordPlayer);
global.genius = new Genius.Client();
player.extractors.loadDefault()

require('./src/loader');

client.login(client.config.app.token);
```

This should fix the error, and the bot should actually work find if you add this to beta, as I have encountered 0 issues so far with this being the only change I made. The changes made allows the extractor to work and not crash with the extractor error. Also recent changes to both discord and discord-player has been made so that the music can now be played there.

**Comment by pendragons-code** [comment]
It is worth noting that the docs recommend doing this in an async manner, having awaits before the loading of extractors.

**Comment by Nickeldon** [comment]
https://discord.com/channels/773639842449850368/1102793257450225684/1103288193949913098

**Comment by pendragons-code** [comment]
> https://discord.com/channels/773639842449850368/1102793257450225684/1103288193949913098

ye i know im just leaving it here since they seem to have yet to include it in the beta version, unless im wrong

**Comment by revot334** [comment]
will be added! to beta soon

**Comment by pendragons-code** [comment]
> will be added! to beta soon

nice
