### ISSUE TITLE
YouTube playlists only play the first

### ISSUE THREAD

**Issue by Jaie55** [ZerioDev/Music-bot#289]
Only play the first song of a youtube playlist.
If you put a Spotify playlist works well and play it entirely, but in youtube just the first song.

**Comment by revot334** [comment]
interesting issue... i will try and replicate and hopefully resolve your issue

**Comment by Jaie55** [comment]
Something new about that?

**Comment by revot334** [comment]
closed: no way to replicate error, scraping youtube can be weird
