### ISSUE TITLE
The bot can ping @everyone if you make it play a specific video.

### ISSUE THREAD

**Issue by ItsMrCube** [ZerioDev/Music-bot#29]
For example, if someone makes the bot play a video like [this](https://youtu.be/1Sed9L345gI) the bot will respond with "Currently playing @everyone 🎵"

**Comment by ZerioDev** [comment]
Thank you i will fix this as soon as i can 👍

**Comment by sanikava** [comment]
not done now also 👎 
lol i knwon it is not easy to make hehe

**Comment by ZerioDev** [comment]
Good evening !
Sorry in advance for the delay, the new version is out, I invite you to download the new one.
Remember to use version 2.0.0 of the code now. Just restart the download of the source code.
Good evening to you and good use 👋
