### ISSUE TITLE
The music keep cutting

### ISSUE THREAD

**Issue by WistfulPerson** [ZerioDev/Music-bot#290]
The music keep cutting and the control menu repeats the bot is hosted is it from the hosting service or something else?

**Comment by Nickeldon** [comment]
The "music keeps cutting" symptom is more likely due to a fault in the streaming APIs which are ytdl-core combined with opus/ffmpeg. The repeating control menu is a new one... Do you use the beta or main branch of the Zerio Bot?

**Comment by CharliePlayz** [comment]
I have the same problem and using the main branch

**Comment by WistfulPerson** [comment]
> The "music keeps cutting" symptom is more likely due to a fault in the streaming APIs which are ytdl-core combined with opus/ffmpeg. The repeating control menu is a new one... Do you use the beta or main branch of the Zerio Bot?

i use the main

**Comment by Nickeldon** [comment]
May you use the beta branch? The main branch has numerous bugs because of the latest versions of discord-player and discord-js

**Comment by WistfulPerson** [comment]
oh ok I'll use the beta branch, Thanks for your help <3
