### ISSUE TITLE
Music stopped

### ISSUE THREAD

**Issue by farizrifqi** [ZerioDev/Music-bot#294]
I haven't made any changes except for the bot token.

When I run the bot locally, the music plays until the end without any issues. However, when I run it on my VPS, the bot plays music, but it stops abruptly halfway through without disconnecting from the channel, and there's no error output in the console.

My VPS has the following specifications: 4GB of RAM and 2 vCPUs (Location: USA, my voice channel server on Asia). It shouldn't be a problem, right?

I just want to make sure if someone has any ideas about this issue.

![chanenl](https://cdn.discordapp.com/attachments/1022111390896492606/1164193823635820584/Screenshot_143.png?ex=654252fd&is=652fddfd&hm=b49b87557ae4c7858c4b7d2e19c560a8dc16c8f318b2e7cc19a1090d949d4167&)

**Comment by iGameCreep** [comment]
Usually, when it tells that no more songs are in the queue right after starting playing (no sound emitted), it is related to FFmpeg: try downloading it directly from your VPS or try maybe using Yarn instead of NPM

**Comment by farizrifqi** [comment]
Thanks, I reinstall the FFmpeg from different sources and it works.
