### ISSUE TITLE
Multi language support and command interface

### ISSUE THREAD

**Issue by delidolu1adam** [ZerioDev/Music-bot#298]
Please add multi-language support and update the interface as well. Thanks. <3

![discord_music_bot_play_interface](https://github.com/ZerioDev/Music-bot/assets/6446405/3bd5e763-9385-4694-a16d-de8b86b7c616)

**Comment by iGameCreep** [comment]
Hi !
Is anything wrong with the interface ?
Multi languages can be added, but it would take some time to make all of the translations

**Comment by revot334** [comment]
this is something that it not in the current path way for the bot
