### ISSUE TITLE
[BUG] Typo

### ISSUE THREAD

**Issue by agcrisbp** [ZerioDev/Music-bot#309]
Just wanted to let you know that you have a typo in [emptyChannel.js](https://github.com/ZerioDev/Music-bot/blob/master/events/Player/emptyChannel.js), in the `await Translateslate` section which should be `await Translate` (I think).

**Comment by revot334** [comment]
fixed sorry about that

**Comment by agcrisbp** [comment]
> fixed sorry about that

I just fount a new one in [search.js](https://github.com/ZerioDev/Music-bot/blob/master/commands/music/search.js) line 80.

**Comment by revot334** [comment]
Fixed!

**Comment by Nickeldon** [comment]
😭
