### ISSUE TITLE
TypeError: Cannot read property 'items' of undefined

### ISSUE THREAD

**Issue by joseespartacus** [ZerioDev/Music-bot#31]
When I play I have this error :
![image](https://user-images.githubusercontent.com/59189134/97104483-d8dabd80-1679-11eb-9145-f3b7c5bc1a50.png)

**Comment by ZerioDev** [comment]
Good evening, thank you for that issue !
Indeed it happens to you and others since a few days, it's a problem that actually comes from the module (discord-player).
I invite you to share it with the creator of the module.
Good evening to you, remaining at your disposal 👍

**Comment by joseespartacus** [comment]
ok thanks
