### ISSUE TITLE
add id pls

### ISSUE THREAD

**Issue by HindiaFtNpc** [ZerioDev/Music-bot#310]

**Comment by HindiaFtNpc** [comment]
id lague ( indonesian )

**Comment by Nickeldon** [comment]
What do you mean? Are you reffering to the translation service?

**Comment by HindiaFtNpc** [comment]
yes, add Indonesian <3

**Comment by agcrisbp** [comment]
> yes, add Indonesian <3

It has been added tho.

![Screenshot_2024-05-12-17-21-17-813_com foxdebug acode](https://github.com/ZerioDev/Music-bot/assets/54905291/f6731595-8304-4a22-b5cb-6bfe56ce2adc)

**Comment by Nickeldon** [comment]
> > yes, add Indonesian <3
> 
> It has been added tho.
> 
> ![Screenshot_2024-05-12-17-21-17-813_com foxdebug acode](https://private-user-images.githubusercontent.com/54905291/329842821-f6731595-8304-4a22-b5cb-6bfe56ce2adc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MjgyNjEsIm5iZiI6MTcxNTUyNzk2MSwicGF0aCI6Ii81NDkwNTI5MS8zMjk4NDI4MjEtZjY3MzE1OTUtODMwNC00YTIyLWI1Y2ItNmJmZTU2Y2UyYWRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDE1MzI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3MmUxMDBmZmI3YTdiNmQzZjI3ZmVhNjBmYmFhMWNiNDBkZTU4NjEzMzViNThlNmE1YTZkZDA4ZWFkZjVjZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V67p6JjZLxYcIh3zzNRz0aeemSyc_SbongmizjIbyZ0)

I forgot to add it in the Readme.md file... Will be soon fixed

**Comment by HindiaFtNpc** [comment]
Thank you for adding the ID language
