### ISSUE TITLE
I can't seem to play any music?

### ISSUE THREAD

**Issue by Willasc** [ZerioDev/Music-bot#32]
Whenever I go to play a song the bot joins and is all normal. But doesn't play any song.
![github](https://user-images.githubusercontent.com/68730451/97275369-00a07000-188a-11eb-8a64-d6293168fafc.png)

**Comment by ZerioDev** [comment]
Good evening, thank you for that issue !
Indeed it happens to you and others since a few days, it's a problem that actually comes from the module (discord-player).
I invite you to share it with the creator of the module.
Good evening to you, remaining at your disposal 👍

**Comment by PersonalSlash** [comment]
I'm having the same problem here

**Comment by Damino218** [comment]
+1

**Comment by mkgaming54** [comment]
> Good evening, thank you for that issue !
> Indeed it happens to you and others since a few days, it's a problem that actually comes from the module (discord-player).
> I invite you to share it with the creator of the module.
> Good evening to you, remaining at your disposal 👍

pls help I am also having the same issue

**Comment by docentYT** [comment]
I am have the same issue. Maybe it a problem with api.

**Comment by ZerioDev** [comment]
No this is a problem with ytsr (a module that discord-player) uses.

**Comment by ZerioDev** [comment]
Good evening !
Sorry in advance for the delay, the new version is out, I invite you to download the new one.
Remember to use version 2.0.0 of the code now. Just restart the download of the source code.
Good evening to you and good use 👋
