### ISSUE TITLE
It's aren't working 

### ISSUE THREAD

**Issue by DevBros02** [ZerioDev/Music-bot#34]
Hai the code is giving error */
/*
 * validateURL will be renamed to validateID to match with getPlaylistID in the next release of ytpl *
 *                   set ytpl.do_warn_deprecate = false to disable this message                    *
 *
Can u help us. I tried your discord but it's not working 
Can u contact me plz SoulStonePlays#6388

**Comment by ZerioDev** [comment]
Good evening, thank you for that issue !
I am currently redoing all the code to put it back online very soon. 
This problem is already solved for me. I will soon publish the update of this one.
Good evening to you, remaining at your disposal 👍

**Comment by DevBros02** [comment]
Ok

**Comment by JakeCodes** [comment]
It still shows 
/***************************************************************************************************** 
 * validateURL will be renamed to validateID to match with getPlaylistID in the next release of ytpl * 
 *                   set `ytpl.do_warn_deprecate = false` to disable this message                    * 
 *****************************************************************************************************/

**Comment by ZerioDev** [comment]
Good evening !
Sorry in advance for the delay, the new version is out, I invite you to download the new one.
Remember to use version 2.0.0 of the code now. Just restart the download of the source code.
Good evening to you and good use 👋
