### ISSUE TITLE
Emoji

### ISSUE THREAD

**Issue by FallenSankta** [ZerioDev/Music-bot#341]
tried switching the emojis using the format <:emoji-name:emoji-id>, but instead it just 
```
emojis:{
        'back': '<:emoji-name:emoji-id>',
.....
```
yet the buttons keep showing as "<:emoji-name:emoji-id>" instead of the emoji

**Comment by Johannes7k75** [comment]
A label cant use an guild emoji, you can just use the normal emojis. If you want to use guild emojis for a button you have to use [`.setEmoji()`](https://discord.js.org/docs/packages/discord.js/14.16.3/ButtonBuilder:Class#setEmoji) on a button.

**Comment by FallenSankta** [comment]
thanks for the help
