### ISSUE TITLE
play command error 

### ISSUE THREAD

**Issue by SAMXTG** [ZerioDev/Music-bot#36]
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'createMessageCollector' of undefined
    at /home/runner/Music-bot/node_modules/discord-player/src/Player.js:178:47
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:192) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:192) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ZerioDev** [comment]
Good evening, thank you for that issue !
I am currently redoing all the code to put it back online very soon. 
This problem is already solved for me. I will soon publish the update of this one.
Good evening to you, remaining at your disposal 👍

**Comment by SAMXTG** [comment]
disicord link i need

**Comment by ZerioDev** [comment]
I don't understand 👀

**Comment by SAMXTG** [comment]
invite me

**Comment by SAMXTG** [comment]
you'r discord server

**Comment by ZerioDev** [comment]
I invite you to contact me on discord, my current tag being `!Zerio.js#2020`.

**Comment by SAMXTG** [comment]
i sent you

**Comment by kshitijraj-06** [comment]
same error comes to me.

**Comment by ZerioDev** [comment]
Good evening !
Sorry in advance for the delay, the new version is out, I invite you to download the new one.
Remember to use version 2.0.0 of the code now. Just restart the download of the source code.
Good evening to you and good use 👋
