### ISSUE TITLE
a

### ISSUE THREAD

**Issue by PedroHVe** [ZerioDev/Music-bot#44]
(node:2656) UnhandledPromiseRejectionWarning: Error [TOKEN_INVALID]: An invalid token was provided.
    at WebSocketManager.connect (C:\Users\Windows 10\Desktop\Music-bot-master\node_modules\discord.js\src\client\websocket\WebSocketManager.js:133:26)
    at Client.login (C:\Users\Windows 10\Desktop\Music-bot-master\node_modules\discord.js\src\client\Client.js:223:21)       
(node:2656) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)   
(node:2656) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
PS C:\Users\Windows 10\Desktop\Music-bot-master>

**Comment by PedroHVe** [comment]
but I informed the token in bot.json

**Comment by y0rune** [comment]
Hi!
I think your token is incorrect.

**Comment by Groot3** [comment]
Try generating a new token and putting it in if your current one isn't working, it should fix the issue.
