### ISSUE TITLE
choose music

### ISSUE THREAD

**Issue by Akurejs** [ZerioDev/Music-bot#48]
how to make the song play automatically by name, without having to choose in the text channel which song you want to hear?

**Comment by ZerioDev** [comment]
Good evening!
It is not possible anymore to automatically select the first music with a search.
I think this function will be added to the `discord-player` module soon 👍

**Comment by instag1b** [comment]
Upstream issue: Androz2091/discord-player#186

**Comment by HAPPY7131** [comment]
Because music-player not able to play live because music-player not have stream buffer module

**Comment by ZerioDev** [comment]
Good evening 👋
I am closing this issue because it is on the discord-player project that an issue should be opened.
