### ISSUE TITLE
I am not able to understand how to start the BOT?

### ISSUE THREAD

**Issue by legendaryhercules** [ZerioDev/Music-bot#49]
![image](https://user-images.githubusercontent.com/65266224/101773780-40a67400-3b13-11eb-8461-9df880a580f3.png)

**Comment by ZerioDev** [comment]
Hello, there are several points to resume 🤔 

1) Do not run your program from system 32.
2) You must `cd` the bot folder before you can launch the bot.

**Comment by legendaryhercules** [comment]
Super thx broooo

**Comment by legendaryhercules** [comment]
> Hello, there are several points to resume 🤔
> 
> 1. Do not run your program from system 32.
> 2. You must `cd` the bot folder before you can launch the bot.

thnx man
