### ISSUE TITLE
DJ role

### ISSUE THREAD

**Issue by Red09discord** [ZerioDev/Music-bot#51]
As the title says a DJ role along with a vote skip for people with non-DJ role would be a good addition.

**Comment by ZerioDev** [comment]
Good evening 👋 
Yes this could be a good idea but it won't add on the bot, but i can help you to do it on your bot.

**Comment by ZerioDev** [comment]
Hello 👋
I close this issue due to inactivity, do not hesitate to reopen one if necessary.
