### ISSUE TITLE
Bug commande volume

### ISSUE THREAD

**Issue by Somaxx** [ZerioDev/Music-bot#58]
On peut faire la commande !play Infinity,
Il faudrait patch sa pour les autres ! 😁

**Comment by ZerioDev** [comment]
Bonjour 👋
Je n'ai pas trop compris, c'est normal que l'on puisse utiliser la commande play à de multiples reprises, car celle-ci ajoute dans la queue les musiques à venir.

**Comment by Somaxx** [comment]
Non, par exemple, tu as fait en sorte que on peut mettre le volume entre 0 et 100, mais on peut le mettre en infinity
