### ISSUE TITLE
my bot is joining the vc but no music plays and then it gets disconnected and then error in the terminal of my vs cord plz solve this or give a new code

### ISSUE THREAD

**Issue by djpie123** [ZerioDev/Music-bot#63]

**Comment by MrSuperTop** [comment]
Maybe, if you provide an error someone can help you.

**Comment by SamuelLim1019** [comment]
my bot doesn't play the music requested too.... it just stays quiet. i tried it foor few times alr, still not working

**Comment by gamer50082** [comment]
That happen to me once and I think it will be fix in 24h like how my bot fix

**Comment by ZerioDev** [comment]
Closed for inactivity 🚫
