### ISSUE TITLE
Spotify

### ISSUE THREAD

**Issue by BL3CKM00N** [ZerioDev/Music-bot#68]
When using a Spotify link the bot plays a different song.
this doesn't happen 100% of the time. But it happens often when used

https://pasteboard.co/JJ1gMI0.png

**Comment by Swarwerth** [comment]
Hello 🤙

This issue is normal! When a Spotify Link is motioned, the module `discord-player` search the name of the Spotify song in Youtube. Try to search the name song with the artist directly!
