### ISSUE TITLE
help command not working

### ISSUE THREAD

**Issue by Iliyas-Syed007** [ZerioDev/Music-bot#73]
every commands works but the help command is not working please help me with that.

**Comment by Swarwerth** [comment]
Any error?

**Comment by Itzzz-Malik** [comment]
the help command dosent work
https://user-images.githubusercontent.com/76797986/105894475-5e795b00-6025-11eb-83e7-bb9723b560ca.png

**Comment by ZerioDev** [comment]
Hello 👋

- Did you change anything in the code ?
- What version of discord.js & Node are you using ?

Have a nice evening !

**Comment by Itzzz-Malik** [comment]
Did you change anything in the code : i used the same code

What version of discord.js & Node are you using:  "discord.js": "^12.5.1" ,     "node": "12.x"

**Comment by ZerioDev** [comment]
Try to update your version of Node.

**Comment by Itzzz-Malik** [comment]
Witch Version

**Comment by ZerioDev** [comment]
The latest 👍

**Comment by Itzzz-Malik** [comment]
"node": "14.x"

**Comment by Itzzz-Malik** [comment]
when is the latest coming , i want to make it embed

**Comment by ZerioDev** [comment]
I suggest you come directly to the support server for more detailed help if you want.
You can find the link in the README.

**Comment by ZerioDev** [comment]
Closed for inactivity 🚫
