### ISSUE TITLE
Now Playing Command Not Working

### ISSUE THREAD

**Issue by Itzzz-Malik** [ZerioDev/Music-bot#76]
the now playing command dosent work
https://user-images.githubusercontent.com/76797986/105894475-5e795b00-6025-11eb-83e7-bb9723b560ca.png

**Comment by ZerioDev** [comment]
Hello 👋

- Did you change anything in the code ?
- What version of discord.js & Node are you using ?

Have a nice evening !

**Comment by ZerioDev** [comment]
Problem fixed on the server.
