### ISSUE TITLE
the play command send me two messages.

### ISSUE THREAD

**Issue by Johannes7k75** [ZerioDev/Music-bot#77]
Hear the problem, i have only send one play command 
![image](https://user-images.githubusercontent.com/57235955/105902222-a1840000-601e-11eb-9fb1-415df452b653.png)

**Comment by ZerioDev** [comment]
Hello 👋

- Did you change anything in the code ?
- Does your bot answer twice to other commands (help, ping...) ?

Have a nice evening !

**Comment by Johannes7k75** [comment]
- Help and ping do not send the answer twice.

- And i have changed something in the code

**Comment by ZerioDev** [comment]
I suggest you come directly to the support server for more detailed help if you want.
You can find the link in the README.

**Comment by Johannes7k75** [comment]
I fixed the problem if anyone need help for the same problem write me
