### ISSUE TITLE
I can't hear the music and the Volume command is not working 

### ISSUE THREAD

**Issue by DiscordNoobyDev** [ZerioDev/Music-bot#78]
Please help me I dont know what to do here

**Comment by Natemo6348** [comment]
@DiscordNoobyDev do you get any errors when trying to play music or use the volume command?

**Comment by Natemo6348** [comment]
Also does it join the channel?

**Comment by DiscordNoobyDev** [comment]
it does the music does not play

**Comment by Natemo6348** [comment]
> @DiscordNoobyDev do you get any errors when trying to play music or use the volume command?

I need to know if you get any errors, either on discord or in the console

**Comment by ZerioDev** [comment]
Closed for inactivity 🚫
