### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'url' of undefined

### ISSUE THREAD

**Issue by WhiteSkyAngel** [ZerioDev/Music-bot#8]
When I play a music with an URL and I stop the music I have this error :
![image](https://user-images.githubusercontent.com/44341346/82674134-270b1100-9c43-11ea-9a87-b69595393144.png)

**Comment by Pronicio** [comment]
Hello, I too have this mistake, I'm currently looking for a problem.

**Comment by ZerioDev** [comment]
Hi, sorry I'm late, I'm going to talk to the creator of the module the bot is using !

**Comment by Pronicio** [comment]
Ok, tanks you !

**Comment by ZerioDev** [comment]
Pronicio, j'ai vu que tu parlais Français 👍 

FR : Tu peut d'abord essayer de mettre à jour ytdl-core.
EN : You can try to update ytdl-core first.

**Comment by Pronicio** [comment]
D’accord, j’ai regardé et j’ai mis à jour aussi tous mes module et ça marche !

**Comment by ZerioDev** [comment]
Si tout fonctionne je vais fermer cette issue 👍 
Si vous avez d'autres questions n'hésitez pas !

I'm closing the issue. If you have any further questions, please do not hesitate to contact us.
