### ISSUE TITLE
the prefix resume does not work after typing -resume, it says it does but the song never resumes

### ISSUE THREAD

**Issue by ThePineApplePizza** [ZerioDev/Music-bot#81]

**Comment by kingofsoq** [comment]
same here just see trough discord player, but donow whats wrong.

**Comment by ZerioDev** [comment]
Can you describe more your issue please ?

**Comment by rryuno** [comment]
I have the same problem as well 
when I pause a song and resume it the bot will say song ------ resumed!
but the bot won't play

**Comment by Natemo6348** [comment]
I can reproduce this as well, no error in console or on discord

**Comment by ZerioDev** [comment]
Hey 👋

This happens with Node v15. If it does, install Node v14.
This comes partly with [discord.js](https://github.com/Androz2091/discord-player/issues/252).

**Comment by Natemo6348** [comment]
> Hey 👋
> 
> This happens with Node v15. If it does, install Node v14.
> This comes partly with [discord.js](https://github.com/Androz2091/discord-player/issues/252).

I had and have Node v14, so idk
