### ISSUE TITLE
Not an issue, but a command.

### ISSUE THREAD

**Issue by p-engun** [ZerioDev/Music-bot#82]
I cant figure out how to post in pull requests, so am posting the command here, pretty simple, but hope u can add this as may be useful for some ppl:

New file in the 'infos' folder
module.exports = {
    name: 'invite',
    aliases: ['inv'],
    category: 'Infos',
    utilisation: '{prefix}invite',

    execute(client, message) {
        message.channel.send(`${client.emotes.link} - Invite me: <https://discord.com/oauth2/authorize?client_id=${client.config.discord.client_id}&scope=bot&permissions=2147483647>`);
    },
}; 

In bot.js, add an extra line under the emoji export string:
        link: ':link:',

Also in bot.js, create new line under discord string, like this:
        client_id: 'PASTE CLIENT ID'

**Comment by ZerioDev** [comment]
Hey 👋

I'm closing this issue because we talked about it on the support server.
