### ISSUE TITLE
Not a issue but a question

### ISSUE THREAD

**Issue by Block354** [ZerioDev/Music-bot#83]
Would it be possible to make the bot play Spotify links?

**Comment by ZerioDev** [comment]
Hello 👋

Yes you can use Spotify with this source code.

![image](https://user-images.githubusercontent.com/43386412/107755114-ab964600-6d22-11eb-9bed-d5c6cedc645f.png)

**Comment by Block354** [comment]
Thanks I realized I had not install the bot properly and now it works.
