### ISSUE TITLE
stop sending playing now if loop is enabled

### ISSUE THREAD

**Issue by SuperAmmar77** [ZerioDev/Music-bot#84]
how to stop the bot from sending playing **song name** every time the bot start the music again while loop is enabled ?

**Comment by Twenty2kay** [comment]
if (client.player.getQueue(message).repeatMode == true) return

**Comment by Twenty2kay** [comment]
Make sure to join the support server for help

**Comment by ZerioDev** [comment]
Hey 👋

You can add this in `player > trackStart.js` :

```js
if (client.player.getQueue(message).repeatMode) return;```

**Comment by Twenty2kay** [comment]
👍
