### ISSUE TITLE
FFmpeg/avconv not found!

### ISSUE THREAD

**Issue by SmugTheKiler** [ZerioDev/Music-bot#85]
Theres this thing... Saying the other thing isn't found.

**Comment by Coder-TheSid** [comment]
You need Download FFmpeg.

**Comment by Ryan-Ray-Offical** [comment]
> You need Download FFmpeg.

Could you tell me a good guide to download it?

**Comment by SmugTheKiler** [comment]
hi?


пн, 15 февр. 2021 г. в 08:18, Ryan-Ray-Offical <notifications@github.com>:

**Comment by Swarwerth** [comment]
> > You need Download FFmpeg.
> 
> Could you tell me a good guide to download it?

https://blog.gregzaal.com/how-to-install-ffmpeg-on-window
