### ISSUE TITLE
ffmpeg error 

### ISSUE THREAD

**Issue by Zachron-Official** [ZerioDev/Music-bot#87]
Errors:
`Emitted 'error' event on ChildProcess instance at:`

`Error: spawn ffmpeg ENOENT`

Anyone know how to fix this?

**Comment by Swarwerth** [comment]
You need to install FFMPEG by [this link](https://blog.gregzaal.com/how-to-install-ffmpeg-on-windows), or with `npm i ffmpeg-static`

**Comment by adgjmptw2** [comment]
![image](https://user-images.githubusercontent.com/41006577/108068594-a1b76e80-70a5-11eb-8ac7-f44937a996cf.png)
![image](https://user-images.githubusercontent.com/41006577/108068600-a419c880-70a5-11eb-9a76-1fa8d866b2d1.png)
how to fix?
