### ISSUE TITLE
error

### ISSUE THREAD

**Issue by adgjmptw2** [ZerioDev/Music-bot#88]
![image](https://user-images.githubusercontent.com/41006577/108064796-839b3f80-70a0-11eb-9b76-eb628369f781.png)
how to fix it ?

**Comment by Swarwerth** [comment]
You need to install FFMPEG by [this link](https://blog.gregzaal.com/how-to-install-ffmpeg-on-windows), or with `npm i ffmpeg-static`

#87

**Comment by adgjmptw2** [comment]
![image](https://user-images.githubusercontent.com/41006577/108068929-18ed0280-70a6-11eb-9f5f-492335dbd8dd.png)
![image](https://user-images.githubusercontent.com/41006577/108068906-112d5e00-70a6-11eb-8088-a8b5a7fc2bbd.png)
how to fix?

**Comment by Swarwerth** [comment]
`npm i`

**Comment by adgjmptw2** [comment]
thx

**Comment by adgjmptw2** [comment]
good work nice
