### ISSUE TITLE
not a issue but need help with discord player

### ISSUE THREAD

**Issue by AnshhSingh** [ZerioDev/Music-bot#91]
I am making a bot with similar structure to this one I wanted to ask that how can I use these options 
![Screenshot_20210220-142655_Chrome](https://user-images.githubusercontent.com/28798608/108590157-13ced280-7388-11eb-8a5f-197b27e2bb5a.png)
(this is from the documentation of discord player)

**Comment by Swarwerth** [comment]
In the `index.js` file, you can ad this propreties by replacing 
```js
client.player = new Player(client);
```

by, for example, this : 
```js
client.player = new Player(client, {leaveOnEnd: false, leaveOnEmpty: false});
```

**Comment by AnshhSingh** [comment]
thanks a lot, stared this repository :)
