### ISSUE TITLE
Keep Bot Playing with empty channel

### ISSUE THREAD

**Issue by simonebartoli** [ZerioDev/Music-bot#95]
I was asking myself if is it possible to keep the bot running 24/7 even if noone is more in the voice channel.

If it is not a default option but it's possible could you tell me how to do it?

**Comment by Coder-TheSid** [comment]
const player = new Player(client, {
	leaveOnEmpty: false, 
});

**Comment by Swarwerth** [comment]
![image](https://user-images.githubusercontent.com/26115962/109029637-56174d00-76c3-11eb-954e-d54292fad1ba.png)

**Comment by simonebartoli** [comment]
Thank you all for the quick response 👍
