### ISSUE TITLE
Suddenly getting some errors

### ISSUE THREAD

**Issue by AnshhSingh** [ZerioDev/Music-bot#98]
![Screenshot_20210228-222917_Chrome](https://user-images.githubusercontent.com/28798608/109426589-7c672080-7a14-11eb-9f18-2c8e9113289e.png)

**Comment by Flosfratz** [comment]
Please update Nodejs to v14. Then it should be fixed.

**Comment by AnshhSingh** [comment]
yes actually o know that but is there a way to work around it because I want to use nodejs 12.x for some purpose

**Comment by Swarwerth** [comment]
> yes actually I know that but is there a way to work around it because I want to use nodejs 12.x for some purpose

`discord-player`, the module used by Music-bot work only with Node.js v.14.x

**Comment by AnshhSingh** [comment]
all right well I get it
thanks
